(function (root) {
  "use strict";
  const PA=root.PHOTOACOUSTIC,C=PA.Core,A=PA.Audio;
  const Q15=32768,Q20=1048576,PPM=1000000;

  const MATERIALS=Object.freeze({
    soot:Object.freeze({id:"soot",name:"Soot / candle black",absorptionPpm:980000,tauUs:1500,gruneisenPpm:400000,expansionPpm:1200000,nonlinearityPpm:150000,comment:"Classic jar absorber—broadband and slightly gritty."}),
    charcoal:Object.freeze({id:"charcoal",name:"Charcoal",absorptionPpm:950000,tauUs:4000,gruneisenPpm:550000,expansionPpm:1000000,nonlinearityPpm:250000,comment:"Slower thermal response, warm body, stronger saturation."}),
    gas_ethene:Object.freeze({id:"gas_ethene",name:"Ethene gas cell",absorptionPpm:600000,tauUs:800,gruneisenPpm:800000,expansionPpm:1500000,nonlinearityPpm:50000,comment:"Fast, clean response suited to notes and high-frequency modulation."}),
    pdms_composite:Object.freeze({id:"pdms_composite",name:"CS/PDMS nanocomposite",absorptionPpm:900000,tauUs:300,gruneisenPpm:1200000,expansionPpm:800000,nonlinearityPpm:100000,comment:"Fast and efficient illustrative solid absorber with a bright edge."}),
    black_aluminum:Object.freeze({id:"black_aluminum",name:"Black aluminium foil",absorptionPpm:850000,tauUs:8000,gruneisenPpm:300000,expansionPpm:700000,nonlinearityPpm:400000,comment:"Heavy thermal mass—dark, bass-oriented and nonlinear."}),
    custom:Object.freeze({id:"custom",name:"Custom material",absorptionPpm:1000000,tauUs:2000,gruneisenPpm:500000,expansionPpm:1000000,nonlinearityPpm:100000,comment:"User-defined illustrative material."})
  });
  const RESONATORS=Object.freeze({
    jar:Object.freeze({id:"jar",name:"Glass jar",frequenciesMilli:Object.freeze([180000,360000,720000,1100000]),qMilli:Object.freeze([8000,6000,5000,4000]),gainPpm:1200000,comment:"Mid-emphasised soot-jar modes with a natural roomy character."}),
    helmholtz:Object.freeze({id:"helmholtz",name:"Helmholtz resonator",frequenciesMilli:Object.freeze([110000,220000]),qMilli:Object.freeze([15000,10000]),gainPpm:1500000,comment:"Strong low-mid resonance with long, boomy decay."}),
    h_cell:Object.freeze({id:"h_cell",name:"H-type PA cell",frequenciesMilli:Object.freeze([250000,500000,1000000,2000000]),qMilli:Object.freeze([20000,18000,12000,8000]),gainPpm:1800000,comment:"High-Q scientific-cell illustration with clear ringing modes."}),
    open_air:Object.freeze({id:"open_air",name:"Open-air approximation",frequenciesMilli:Object.freeze([1000000]),qMilli:Object.freeze([700]),gainPpm:600000,comment:"Broad 1 kHz response inherited from the Python model; not a flat physical free field."}),
    industrial_pipe:Object.freeze({id:"industrial_pipe",name:"Industrial pipe / duct",frequenciesMilli:Object.freeze([85000,170000,340000,680000,1360000]),qMilli:Object.freeze([12000,10000,8000,6000,4000]),gainPpm:1400000,comment:"Longitudinal pipe modes for mechanical and industrial textures."}),
    custom:Object.freeze({id:"custom",name:"Custom resonator",frequenciesMilli:Object.freeze([440000]),qMilli:Object.freeze([10000]),gainPpm:1000000,comment:"User-defined parallel resonator modes."})
  });
  const DEMO_SCHEDULE=Object.freeze([
    Object.freeze({startNumerator:0,startDenominator:1,endNumerator:4,endDenominator:15,materialId:"soot",resonatorId:"jar",laserPowerPpm:1000000}),
    Object.freeze({startNumerator:4,startDenominator:15,endNumerator:22,endDenominator:45,materialId:"charcoal",resonatorId:"industrial_pipe",laserPowerPpm:1300000}),
    Object.freeze({startNumerator:22,startDenominator:45,endNumerator:32,endDenominator:45,materialId:"gas_ethene",resonatorId:"h_cell",laserPowerPpm:900000}),
    Object.freeze({startNumerator:32,startDenominator:45,endNumerator:1,endDenominator:1,materialId:"pdms_composite",resonatorId:"open_air",laserPowerPpm:1500000})
  ]);
  const PRESETS=Object.freeze({
    "industrial-fib":Object.freeze({id:"industrial-fib",name:"Industrial Fibonacci",description:"Fibonacci optical impulses through charcoal and an industrial pipe, with controlled grit and chamber reflections.",generator:"fibonacci",material:"charcoal",resonator:"industrial_pipe",laserPowerPpm:1400000,derivative:true,bpmMilli:210000,pulse1Milli:3500,pulse2Milli:1800,pulseWidthUs:4000,fibDepth:9,shape:"gaussian",fx:{distortion:true,driveMilli:2200,distMixPpm:400000,eq:false,chorus:false,chorusMixPpm:0,reverb:true,reverbWetPpm:400000,eqLowPpm:1000000,eqMidPpm:1000000,eqHighPpm:1000000}}),
    "soot-music":Object.freeze({id:"soot-music",name:"Soot Music",description:"A fixed pure-tone melody treated as modulated light and heard through a classic soot-and-glass-jar model.",generator:"melody",material:"soot",resonator:"jar",laserPowerPpm:1100000,derivative:false,bpmMilli:90000,pulse1Milli:8000,pulse2Milli:12500,pulseWidthUs:3000,fibDepth:8,shape:"gaussian",fx:{distortion:false,driveMilli:2200,distMixPpm:0,eq:false,chorus:false,chorusMixPpm:0,reverb:true,reverbWetPpm:250000,eqLowPpm:1000000,eqMidPpm:1000000,eqHighPpm:1000000}}),
    "resonant-gas":Object.freeze({id:"resonant-gas",name:"Resonant Gas Cell",description:"A chopped four-note chord exciting an illustrative ethene gas absorber and high-Q H-cell.",generator:"chord-chop",material:"gas_ethene",resonator:"h_cell",laserPowerPpm:900000,derivative:true,bpmMilli:90000,pulse1Milli:4500,pulse2Milli:0,pulseWidthUs:3000,fibDepth:8,shape:"rectangular",fx:{distortion:false,driveMilli:2200,distMixPpm:0,eq:true,chorus:false,chorusMixPpm:0,reverb:false,reverbWetPpm:0,eqLowPpm:700000,eqMidPpm:1400000,eqHighPpm:1200000}}),
    "ultrasonic-edge":Object.freeze({id:"ultrasonic-edge",name:"Ultrasonic Edge",description:"Fast dual optical pulses through the rapid CS/PDMS model, producing a bright granular audio-band edge.",generator:"dual-pulse",material:"pdms_composite",resonator:"open_air",laserPowerPpm:1800000,derivative:true,bpmMilli:90000,pulse1Milli:45000,pulse2Milli:67000,pulseWidthUs:800,fibDepth:8,shape:"gaussian",fx:{distortion:true,driveMilli:1800,distMixPpm:300000,eq:false,chorus:true,chorusMixPpm:250000,reverb:false,reverbWetPpm:0,eqLowPpm:1000000,eqMidPpm:1000000,eqHighPpm:1000000}}),
    "drone-dark":Object.freeze({id:"drone-dark",name:"Dark Thermal Drone",description:"A slow industrial light sequence through heavy black aluminium and Helmholtz modes.",generator:"industrial",material:"black_aluminum",resonator:"helmholtz",laserPowerPpm:1600000,derivative:true,bpmMilli:60000,pulse1Milli:8000,pulse2Milli:12500,pulseWidthUs:3000,fibDepth:7,shape:"gaussian",fx:{distortion:false,driveMilli:2200,distMixPpm:0,eq:true,chorus:false,chorusMixPpm:0,reverb:true,reverbWetPpm:500000,eqLowPpm:1400000,eqMidPpm:900000,eqHighPpm:600000}}),
    "evolving-demo":Object.freeze({id:"evolving-demo",name:"Evolving Material Demo",description:"One industrial light signal evolves from soot/jar to charcoal/pipe, ethene/H-cell and CS/PDMS/open response.",generator:"industrial",material:"soot",resonator:"jar",laserPowerPpm:1000000,derivative:true,bpmMilli:88000,pulse1Milli:8000,pulse2Milli:12500,pulseWidthUs:3000,fibDepth:7,shape:"gaussian",fx:{distortion:false,driveMilli:2200,distMixPpm:0,eq:true,chorus:false,chorusMixPpm:0,reverb:true,reverbWetPpm:280000,eqLowPpm:1100000,eqMidPpm:1250000,eqHighPpm:950000}}),
    "pulse-lab":Object.freeze({id:"pulse-lab",name:"Pulse Laboratory",description:"Two editable pulse trains provide a direct optical excitation playground.",generator:"dual-pulse",material:"soot",resonator:"jar",laserPowerPpm:1000000,derivative:true,bpmMilli:90000,pulse1Milli:8000,pulse2Milli:12500,pulseWidthUs:3000,fibDepth:8,shape:"gaussian",fx:{distortion:false,driveMilli:2200,distMixPpm:400000,eq:false,chorus:false,chorusMixPpm:250000,reverb:true,reverbWetPpm:350000,eqLowPpm:1000000,eqMidPpm:1000000,eqHighPpm:1000000}}),
    "tone-lab":Object.freeze({id:"tone-lab",name:"Tone Laboratory",description:"A pure optical carrier for exposing absorber response and cavity coloration.",generator:"tone",material:"gas_ethene",resonator:"h_cell",laserPowerPpm:900000,derivative:false,bpmMilli:90000,pulse1Milli:8000,pulse2Milli:12500,pulseWidthUs:3000,fibDepth:8,shape:"gaussian",fx:{distortion:false,driveMilli:2200,distMixPpm:0,eq:false,chorus:false,chorusMixPpm:0,reverb:false,reverbWetPpm:0,eqLowPpm:1000000,eqMidPpm:1000000,eqHighPpm:1000000}}),
    "wav-through":Object.freeze({id:"wav-through",name:"WAV Through Light",description:"A local WAV becomes positive-biased light modulation before the selected absorber and acoustic cell.",generator:"wav",material:"soot",resonator:"jar",laserPowerPpm:1000000,derivative:true,bpmMilli:90000,pulse1Milli:8000,pulse2Milli:12500,pulseWidthUs:3000,fibDepth:8,shape:"gaussian",fx:{distortion:false,driveMilli:2200,distMixPpm:0,eq:false,chorus:false,chorusMixPpm:0,reverb:true,reverbWetPpm:350000,eqLowPpm:1000000,eqMidPpm:1000000,eqHighPpm:1000000}})
  });
  for(const preset of Object.values(PRESETS))Object.freeze(preset.fx);

  function copyMaterial(id){const value=MATERIALS[id];if(!value)throw new Error("Unknown material: "+id);return{id:value.id,absorptionPpm:value.absorptionPpm,tauUs:value.tauUs,gruneisenPpm:value.gruneisenPpm,expansionPpm:value.expansionPpm,nonlinearityPpm:value.nonlinearityPpm};}
  function copyResonator(id){const value=RESONATORS[id];if(!value)throw new Error("Unknown resonator: "+id);return{id:value.id,frequenciesMilli:Array.from(value.frequenciesMilli),qMilli:Array.from(value.qMilli),gainPpm:value.gainPpm};}
  function validate(config){
    if(!Object.values(PA.MODES).includes(config.mode))throw new Error("Unsupported determinism mode");
    if(!PRESETS[config.presetId])throw new Error("Unsupported preset ID");
    if(typeof config.seed!=="string"||!config.seed.length||config.seed.length>96)throw new Error("Seed must contain 1–96 characters");
    if(!Number.isInteger(config.mutation)||config.mutation<0||config.mutation>2147483647)throw new Error("Mutation index outside range");
    if(!Number.isInteger(config.sampleRate)||config.sampleRate<8000||config.sampleRate>96000)throw new Error("Sample rate outside 8–96 kHz");
    if(!Number.isSafeInteger(config.durationSamples)||config.durationSamples<2||config.durationSamples>config.sampleRate*120)throw new Error("Duration must be 2 samples to 120 seconds");
    const m=config.material,r=config.resonator;
    if(!m||!r||!config.generator||!config.fx)throw new Error("Incomplete render configuration");
    if(!MATERIALS[m.id]||!RESONATORS[r.id])throw new Error("Unsupported material or resonator ID");
    for(const [name,value,min,max] of [["absorption",m.absorptionPpm,0,2000000],["thermal tau",m.tauUs,10,100000],["Gruneisen",m.gruneisenPpm,0,3000000],["expansion",m.expansionPpm,0,3000000],["nonlinearity",m.nonlinearityPpm,0,1000000],["laser power",config.laserPowerPpm,0,4000000]])if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error("Invalid "+name);
    if(!Array.isArray(r.frequenciesMilli)||!r.frequenciesMilli.length||r.frequenciesMilli.length>8||r.frequenciesMilli.length!==r.qMilli.length)throw new Error("Resonator requires 1–8 matched frequency/Q modes");
    if(!Number.isSafeInteger(r.gainPpm)||r.gainPpm<0||r.gainPpm>4000000)throw new Error("Invalid resonator gain");
    for(let i=0;i<r.frequenciesMilli.length;i+=1){if(!Number.isSafeInteger(r.frequenciesMilli[i])||r.frequenciesMilli[i]<=0||r.frequenciesMilli[i]>=config.sampleRate*500)throw new Error("Resonance outside Nyquist");if(!Number.isSafeInteger(r.qMilli[i])||r.qMilli[i]<100||r.qMilli[i]>100000)throw new Error("Q factor outside 0.1–100");if(config.mode===PA.MODES.STRICT&&(r.frequenciesMilli[i]>=Math.floor(config.sampleRate*1000/6)||r.qMilli[i]<500))throw new Error("Strict resonator mode is outside the fixed-point stability domain");}
    const g=config.generator,generatorTypes=["fibonacci","dual-pulse","melody","chord-chop","tone","industrial","wav"],shapes=["gaussian","exponential","rectangular"];
    if(!generatorTypes.includes(g.type))throw new Error("Unsupported light generator");
    if(PRESETS[config.presetId].generator!==g.type)throw new Error("Preset and generator type disagree");
    if(!shapes.includes(g.pulseShape))throw new Error("Unsupported pulse shape");
    for(const [name,value,min,max] of [["BPM",g.bpmMilli,20000,300000],["tone frequency",g.toneMilli,10000,12000000],["primary pulse rate",g.pulse1Milli,0,500000],["secondary pulse rate",g.pulse2Milli,0,500000],["pulse width",g.pulseWidthUs,20,250000],["Fibonacci depth",g.fibDepth,2,16]])if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error("Invalid "+name);
    if(g.pulse1Milli>0&&g.pulse1Milli<50||g.pulse2Milli>0&&g.pulse2Milli<50)throw new Error("Nonzero pulse rates must be at least 0.05 Hz");
    if(["dual-pulse","fibonacci"].includes(g.type)){const width=Math.max(1,Math.floor(g.pulseWidthUs*config.sampleRate/1000000)),seconds=config.durationSamples/config.sampleRate,operations=Math.ceil(seconds*g.pulse1Milli/1000)*width+Math.ceil(seconds*g.pulse2Milli/1000)*width;if(operations>8000000)throw new Error("Pulse configuration exceeds the deterministic operation budget");}
    if(typeof config.derivative!=="boolean")throw new Error("Pressure derivative flag must be boolean");
    const fx=config.fx;for(const key of ["distortion","eq","chorus","reverb"])if(typeof fx[key]!=="boolean")throw new Error("FX switches must be boolean");for(const [name,value,min,max] of [["drive",fx.driveMilli,1000,12000],["distortion mix",fx.distMixPpm,0,1000000],["chorus mix",fx.chorusMixPpm,0,900000],["reverb wet",fx.reverbWetPpm,0,900000],["EQ low",fx.eqLowPpm,0,3000000],["EQ mid",fx.eqMidPpm,0,3000000],["EQ high",fx.eqHighPpm,0,3000000]])if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error("Invalid "+name);
    if(g.type==="wav"){if(!config.source)throw new Error("WAV Through Light requires a source file");if(config.mode===PA.MODES.STRICT&&!config.source.strictCompatible)throw new Error("Canonical Strict accepts integer PCM WAV only");if(!Number.isInteger(config.source.frames)||config.source.frames<1||!Number.isInteger(config.source.sampleRate)||config.source.samples.length!==config.source.frames||config.source.samplesQ15.length!==config.source.frames)throw new Error("Invalid decoded WAV source");const expected=Math.max(2,Math.round(config.source.frames*config.sampleRate/config.source.sampleRate));if(expected!==config.durationSamples)throw new Error("Recipe duration does not match resampled WAV frame count");}
    return true;
  }
  function seeded(config){const bytes=C.sha256Bytes(C.utf8(config.seed+"\0"+config.mutation));const view=new DataView(bytes.buffer);return{phase:view.getUint32(0,true),offset:view.getUint32(4,true)};}
  async function chunks(length,body,ctx,start,end,label){const size=65536;for(let base=0;base<length;base+=size){const stop=Math.min(length,base+size);for(let i=base;i<stop;i+=1)body(i);if(stop<length)await C.checkpoint(ctx.signal,ctx.progress,start+(end-start)*stop/length,label);}await C.checkpoint(ctx.signal,ctx.progress,end,label);}
  function pulseValueFloat(position,length,shape){if(position<0||position>=length)return 0;if(shape==="rectangular")return 1;if(shape==="exponential")return Math.exp(-5*position/Math.max(1,length-1));const centered=position-length/2,sigma=Math.max(length/6,1e-9);return Math.exp(-.5*(centered/sigma)*(centered/sigma));}
  function pulseValueStrict(position,length,shape){if(position<0||position>=length)return 0;if(shape==="rectangular")return Q15-1;if(shape==="exponential"){const x=C.roundDiv(position*6*Q15,Math.max(1,length));const denominator=Q15+x;return C.roundDiv((Q15-1)*Q15*Q15,denominator*denominator);}const distance=Math.abs(2*position-length),x=C.roundDiv(distance*Q15,Math.max(1,length)),base=Math.max(0,Q15-C.roundDiv(x*x,Q15));return C.roundDiv(base*base,Q15);}
  function fillPulseFloat(out,sr,rateMilli,widthUs,amplitude,shape,offsetSeed){if(rateMilli<=0)return;const rate=rateMilli/1000,period=sr/rate,width=Math.max(1,Math.floor(widthUs*sr/1000000)),offset=(offsetSeed>>>0)%Math.max(1,Math.floor(period));for(let start=offset;start<out.length;start+=period){const i0=Math.floor(start);for(let j=0;j<width&&i0+j<out.length;j+=1)out[i0+j]+=amplitude*pulseValueFloat(j,width,shape);}}
  function fillPulseStrict(out,sr,rateMilli,widthUs,amplitudeQ15,shape,offsetSeed){if(rateMilli<=0)return;const periodNum=BigInt(sr)*1000n,rate=BigInt(rateMilli),width=Math.max(1,Math.floor(widthUs*sr/1000000));let k=0n;const initial=BigInt((offsetSeed>>>0)%Math.max(1,Math.floor(sr*1000/rateMilli)));while(true){const i0=Number(initial+(k*periodNum)/rate);if(i0>=out.length)break;for(let j=0;j<width&&i0+j<out.length;j+=1)out[i0+j]+=C.roundDiv(amplitudeQ15*pulseValueStrict(j,width,shape),Q15);k+=1n;}}
  function fibonacciTimes(rateMilli,length,sr,depth){const fib=[1,1];while(fib.length<depth)fib.push(fib[fib.length-1]+fib[fib.length-2]);const unitSamples=Math.max(1,Math.round(sr*1000/rateMilli)),times=[];let at=0,index=0;while(at<length){times.push(at);at+=fib[index%fib.length]*unitSamples;index+=1;}return times;}
  function fillFibFloat(out,sr,g,seed){const width=Math.max(1,Math.floor(g.pulseWidthUs*sr/1000000));for(const i0 of fibonacciTimes(g.pulse1Milli,out.length,sr,g.fibDepth)){for(let j=0;j<width&&i0+j<out.length;j+=1)out[i0+j]+=pulseValueFloat(j,width,g.pulseShape);}fillPulseFloat(out,sr,g.pulse2Milli,12000,.15,"exponential",seed.offset);}
  function fillFibStrict(out,sr,g,seed){const width=Math.max(1,Math.floor(g.pulseWidthUs*sr/1000000));for(const i0 of fibonacciTimes(g.pulse1Milli,out.length,sr,g.fibDepth)){for(let j=0;j<width&&i0+j<out.length;j+=1)out[i0+j]+=pulseValueStrict(j,width,g.pulseShape);}fillPulseStrict(out,sr,g.pulse2Milli,12000,4915,"exponential",seed.offset);}
  function melodyEvents(){return[[0,1.5,220],[1.5,1.5,277],[3,1.5,330],[4.5,2,440],[6.5,1,330],[7.5,1,277],[8.5,2.5,220],[11,1.5,165],[12.5,3,110]];}
  async function generateFloat(config,ctx){
    const n=config.durationSamples,sr=config.sampleRate,g=config.generator,random=seeded(config);let out;
    if(g.type==="wav"){out=A.resampleFloat(config.source.samples,config.source.sampleRate,sr);let mean=0;for(const v of out)mean+=v;mean/=out.length;let peak=1e-12;for(let i=0;i<out.length;i+=1){out[i]-=mean;peak=Math.max(peak,Math.abs(out[i]));}for(let i=0;i<out.length;i+=1)out[i]=.5+.45*out[i]/peak;await C.checkpoint(ctx.signal,ctx.progress,.12,"decoded light source");return out;}
    out=new Float64Array(n);
    if(g.type==="fibonacci")fillFibFloat(out,sr,g,random);
    else if(g.type==="dual-pulse"){fillPulseFloat(out,sr,g.pulse1Milli,g.pulseWidthUs,1,g.pulseShape,random.offset);fillPulseFloat(out,sr,g.pulse2Milli,Math.max(100,Math.floor(g.pulseWidthUs*.625)),.4,"exponential",random.offset>>>3);}
    else if(g.type==="melody"){
      for(const [start,duration,freq] of melodyEvents()){const i0=Math.floor(start*sr),count=Math.min(Math.floor(duration*sr),n-i0),inc=2*Math.PI*freq/sr;for(let j=0;j<count;j+=1){const env=Math.min(1,j/Math.max(1,.005*sr),(count-j-1)/Math.max(1,.03*sr));out[i0+j]+=.85*Math.sin(inc*j)*Math.max(0,env);const h=Math.sin(inc*1.5*j);out[i0+j]+=.175*h*Math.max(0,env);}}
    } else if(g.type==="chord-chop"){
      const freqs=[110,165,220,277],phase=random.phase/4294967296*2*Math.PI;await chunks(n,i=>{const chop=(Math.sin(2*Math.PI*4.5*i/sr)>=0)?1:0;let value=0;for(const f of freqs)value+=Math.sin(2*Math.PI*f*i/sr+phase);out[i]=.7*value/freqs.length*chop;},ctx,.02,.12,"modulating chord light");return out;
    } else if(g.type==="tone"){
      const phase=random.phase/4294967296*2*Math.PI,inc=2*Math.PI*g.toneMilli/1000/sr;await chunks(n,i=>{out[i]=.8*Math.sin(phase+inc*i);},ctx,.02,.12,"synthesizing optical carrier");return out;
    } else {
      const bpm=g.bpmMilli/1000,phase=random.phase/4294967296*2*Math.PI;fillPulseFloat(out,sr,Math.round(bpm/60*1000),8000,.7,"exponential",random.offset);fillPulseFloat(out,sr,Math.round(bpm/60*4*1000),1500,.21,"gaussian",random.offset>>>2);const fibConfig=Object.assign({},g,{pulse1Milli:Math.round(bpm/60*2*1000),pulseWidthUs:3000,fibDepth:7,pulseShape:"gaussian",pulse2Milli:0});fillFibFloat(out,sr,fibConfig,{offset:0});await chunks(n,i=>{const t=i/sr,drone=.3+.2*Math.sin(2*Math.PI*.07*t)+.1*Math.sin(2*Math.PI*.13*t),sweepFreq=80+40*Math.sin(2*Math.PI*.05*t);out[i]+=.4*drone+.15*Math.sin(phase+2*Math.PI*sweepFreq*t)*(.5+.5*Math.sin(2*Math.PI*.2*t));out[i]=C.clamp(out[i],0,1.2);},ctx,.02,.12,"synthesizing industrial light");return out;
    }
    await C.checkpoint(ctx.signal,ctx.progress,.12,"light source ready");return out;
  }
  async function generateStrict(config,ctx){
    const n=config.durationSamples,sr=config.sampleRate,g=config.generator,random=seeded(config);let out;
    if(g.type==="wav"){out=A.resampleStrict(config.source.samplesQ15,config.source.sampleRate,sr);let sum=0;for(const v of out)sum+=v;const mean=C.roundDiv(sum,out.length);let peak=1;for(let i=0;i<out.length;i+=1){out[i]-=mean;peak=Math.max(peak,Math.abs(out[i]));}for(let i=0;i<out.length;i+=1)out[i]=16384+C.roundDiv(out[i]*14745,peak);await C.checkpoint(ctx.signal,ctx.progress,.12,"canonical WAV light decoded");return out;}
    out=new Int32Array(n);
    if(g.type==="fibonacci")fillFibStrict(out,sr,g,random);
    else if(g.type==="dual-pulse"){fillPulseStrict(out,sr,g.pulse1Milli,g.pulseWidthUs,32767,g.pulseShape,random.offset);fillPulseStrict(out,sr,g.pulse2Milli,Math.max(100,Math.floor(g.pulseWidthUs*.625)),13107,"exponential",random.offset>>>3);}
    else if(g.type==="melody"){
      for(const [start,duration,freq] of melodyEvents()){const i0=Math.floor(start*sr),count=Math.min(Math.floor(duration*sr),n-i0),inc=C.phaseIncrement(freq*1000,sr),incH=C.phaseIncrement(Math.round(freq*1500),sr);let p=random.phase,pH=random.phase>>>1;for(let j=0;j<count;j+=1){const attack=Math.max(1,Math.floor(.005*sr)),release=Math.max(1,Math.floor(.03*sr)),env=Math.min(Q15-1,C.roundDiv(j*Q15,attack),C.roundDiv((count-j-1)*Q15,release));out[i0+j]+=C.roundDiv(C.strictSinQ15(p)*27852*env,Q15*Q15)+C.roundDiv(C.strictSinQ15(pH)*5734*env,Q15*Q15);p=(p+inc)>>>0;pH=(pH+incH)>>>0;}}
    } else if(g.type==="chord-chop"){
      const incs=[110000,165000,220000,277000].map(f=>C.phaseIncrement(f,sr)),phases=incs.map((_,i)=>(random.phase+i*0x1f123bb5)>>>0),chopInc=C.phaseIncrement(4500,sr);let chop=random.phase;await chunks(n,i=>{let value=0;for(let k=0;k<incs.length;k+=1){value+=C.strictSinQ15(phases[k]);phases[k]=(phases[k]+incs[k])>>>0;}out[i]=(C.strictSinQ15(chop)>=0)?C.roundDiv(value*22937,4*Q15):0;chop=(chop+chopInc)>>>0;},ctx,.02,.12,"canonical chord light");return out;
    } else if(g.type==="tone"){
      const inc=C.phaseIncrement(g.toneMilli,sr);let phase=random.phase;await chunks(n,i=>{out[i]=C.roundDiv(C.strictSinQ15(phase)*26214,Q15);phase=(phase+inc)>>>0;},ctx,.02,.12,"canonical optical carrier");return out;
    } else {
      const beatMilli=C.roundDiv(g.bpmMilli*1000,60000),fastMilli=beatMilli*4;fillPulseStrict(out,sr,beatMilli,8000,22937,"exponential",random.offset);fillPulseStrict(out,sr,fastMilli,1500,6881,"gaussian",random.offset>>>2);const fibConfig=Object.assign({},g,{pulse1Milli:beatMilli*2,pulseWidthUs:3000,fibDepth:7,pulseShape:"gaussian",pulse2Milli:0});fillFibStrict(out,sr,fibConfig,{offset:0});let slow1=random.phase,slow2=random.phase>>>1,sweepLfo=random.phase^0xa5a5a5a5,ampLfo=random.phase^0x5a5a5a5a,sweepPhase=random.phase;const i1=C.phaseIncrement(70,sr),i2=C.phaseIncrement(130,sr),il=C.phaseIncrement(50,sr),ia=C.phaseIncrement(200,sr);await chunks(n,i=>{const drone=9830+C.roundDiv(C.strictSinQ15(slow1)*6554,Q15)+C.roundDiv(C.strictSinQ15(slow2)*3277,Q15),freqMilli=80000+C.roundDiv(C.strictSinQ15(sweepLfo)*40000,Q15),sweepInc=C.phaseIncrement(freqMilli,sr),amp=16384+C.roundDiv(C.strictSinQ15(ampLfo)*16384,Q15);out[i]+=C.roundDiv(drone*13107,Q15)+C.roundDiv(C.strictSinQ15(sweepPhase)*4915*amp,Q15*Q15);out[i]=C.clampInt(out[i],0,39322);slow1=(slow1+i1)>>>0;slow2=(slow2+i2)>>>0;sweepLfo=(sweepLfo+il)>>>0;ampLfo=(ampLfo+ia)>>>0;sweepPhase=(sweepPhase+sweepInc)>>>0;},ctx,.02,.12,"canonical industrial light");return out;
    }
    await C.checkpoint(ctx.signal,ctx.progress,.12,"canonical light ready");return out;
  }

  function meanFloat(array){let sum=0;for(const value of array)sum+=value;return sum/array.length;}
  function meanInt(array){let sum=0;for(const value of array)sum+=value;return C.roundDiv(sum,array.length);}
  async function transformFloat(light,material,resonator,config,ctx,range){
    const n=light.length,sr=config.sampleRate,absorbed=new Float64Array(n),temp=new Float64Array(n),pressure=new Float64Array(n),acoustic=new Float64Array(n);const start=range?range[0]:.12,span=range?range[1]-range[0]:.64;
    await chunks(n,i=>{let value=material.absorptionPpm/PPM*config.laserPowerPpm/PPM*light[i];const nl=material.nonlinearityPpm/PPM;if(nl>0){const drive=1+3*nl;value=Math.tanh(drive*value)/Math.tanh(drive);value+=nl*.15*value*value;}absorbed[i]=value;},ctx,start,start+span*.12,"optical absorption");
    const alpha=1/(1+material.tauUs/1000000*sr);let state=0;await chunks(n,i=>{state=alpha*absorbed[i]+(1-alpha)*state;temp[i]=state;},ctx,start+span*.12,start+span*.26,"thermal RC response");const tm=meanFloat(temp);for(let i=0;i<n;i+=1)temp[i]-=tm;
    const scale=material.gruneisenPpm/PPM*material.expansionPpm/PPM;await chunks(n,i=>{const direct=scale*temp[i];if(!config.derivative){pressure[i]=direct;return;}let gradient;if(i===0)gradient=scale*(temp[Math.min(1,n-1)]-temp[0]);else if(i===n-1)gradient=scale*(temp[n-1]-temp[n-2]);else gradient=scale*(temp[i+1]-temp[i-1])*.5;pressure[i]=.65*gradient+.35*direct;},ctx,start+span*.26,start+span*.4,"pressure conversion");
    for(let mode=0;mode<resonator.frequenciesMilli.length;mode+=1){const f0=resonator.frequenciesMilli[mode]/1000,q=resonator.qMilli[mode]/1000,omega=2*Math.PI*f0/sr,beta=Math.tan((omega/q)/2),gain=1/(1+beta),b0=1-gain,b2=-b0,a1=-2*gain*Math.cos(omega),a2=2*gain-1;let z1=0,z2=0;await chunks(n,i=>{const y=b0*pressure[i]+z1;z1=-a1*y+z2;z2=b2*pressure[i]-a2*y;acoustic[i]+=y;},ctx,start+span*(.4+.45*mode/resonator.frequenciesMilli.length),start+span*(.4+.45*(mode+1)/resonator.frequenciesMilli.length),"cavity mode "+(mode+1));}
    const gain=resonator.gainPpm/PPM,am=meanFloat(acoustic);for(let i=0;i<n;i+=1)acoustic[i]=(acoustic[i]-am)*gain;await C.checkpoint(ctx.signal,ctx.progress,start+span,"resonator ready");return{absorbed,temp,pressure,acoustic};
  }
  function mulScale(a,b,scale){return C.roundDiv(a*b,scale);}
  async function transformStrict(light,material,resonator,config,ctx,range){
    const n=light.length,sr=config.sampleRate,absorbed=new Int32Array(n),temp=new Int32Array(n),pressure=new Int32Array(n),acoustic=new Int32Array(n);const start=range?range[0]:.12,span=range?range[1]-range[0]:.64;
    await chunks(n,i=>{let value=mulScale(mulScale(light[i],material.absorptionPpm,PPM),config.laserPowerPpm,PPM),nl=material.nonlinearityPpm;if(nl>0){const driven=mulScale(value,PPM+3*nl,PPM),soft=C.roundDiv(driven*Q15,Q15+Math.abs(driven)),quadratic=mulScale(mulScale(soft,soft,Q15),C.roundDiv(nl*15,100),PPM);value=soft+quadratic;}absorbed[i]=C.clampInt(value,-131072,131072);},ctx,start,start+span*.12,"fixed-point absorption");
    const denominator=material.tauUs*sr+1000000,alpha=C.roundDiv(Q20*1000000,denominator);let state=0;await chunks(n,i=>{state+=mulScale(alpha,absorbed[i]-state,Q20);temp[i]=state;},ctx,start+span*.12,start+span*.26,"fixed-point thermal RC");const tm=meanInt(temp);for(let i=0;i<n;i+=1)temp[i]-=tm;
    const directs=new Int32Array(n);for(let i=0;i<n;i+=1)directs[i]=mulScale(mulScale(temp[i],material.gruneisenPpm,PPM),material.expansionPpm,PPM);await chunks(n,i=>{if(!config.derivative){pressure[i]=directs[i];return;}let gradient;if(i===0)gradient=directs[Math.min(1,n-1)]-directs[0];else if(i===n-1)gradient=directs[n-1]-directs[n-2];else gradient=C.roundDiv(directs[i+1]-directs[i-1],2);pressure[i]=C.roundDiv(65*gradient+35*directs[i],100);},ctx,start+span*.26,start+span*.4,"fixed-point pressure");
    for(let mode=0;mode<resonator.frequenciesMilli.length;mode+=1){const freq=resonator.frequenciesMilli[mode],phase=Number((BigInt(freq)*4294967296n)/(BigInt(sr)*2000n))>>>0,fCoeff=C.roundDiv(2*C.strictSinQ15(phase)*Q20,Q15),damp=C.roundDiv(Q20*1000,resonator.qMilli[mode]);let low=0,band=0;await chunks(n,i=>{low=C.clampInt(low+mulScale(fCoeff,band,Q20),-268435456,268435456);const high=C.clampInt(pressure[i]-low-mulScale(damp,band,Q20),-268435456,268435456);band=C.clampInt(band+mulScale(fCoeff,high,Q20),-268435456,268435456);acoustic[i]=C.clampInt(acoustic[i]+band,-268435456,268435456);},ctx,start+span*(.4+.45*mode/resonator.frequenciesMilli.length),start+span*(.4+.45*(mode+1)/resonator.frequenciesMilli.length),"fixed cavity mode "+(mode+1));}
    const am=meanInt(acoustic);for(let i=0;i<n;i+=1)acoustic[i]=mulScale(acoustic[i]-am,resonator.gainPpm,PPM);await C.checkpoint(ctx.signal,ctx.progress,start+span,"fixed resonator ready");return{absorbed,temp,pressure,acoustic};
  }
  function normalizeFloat(input,peak){let maximum=1e-15;for(const v of input)maximum=Math.max(maximum,Math.abs(v));const out=new Float64Array(input.length),gain=peak/maximum;for(let i=0;i<input.length;i+=1)out[i]=input[i]*gain;return out;}
  function normalizeInt(input,peakQ15){let maximum=1;for(const v of input)maximum=Math.max(maximum,Math.abs(v));const out=new Int32Array(input.length);for(let i=0;i<input.length;i+=1)out[i]=C.roundDiv(input[i]*peakQ15,maximum);return out;}
  function fxFloat(input,config){let x=new Float64Array(input),n=x.length,sr=config.sampleRate,fx=config.fx;if(fx.distortion){const drive=fx.driveMilli/1000,mix=fx.distMixPpm/PPM,tanh=Math.tanh(drive);for(let i=0;i<n;i+=1)x[i]=(1-mix)*x[i]+mix*Math.tanh(drive*x[i])/tanh;x=normalizeFloat(x,.95);}if(fx.eq){const low=new Float64Array(n),highLow=new Float64Array(n),midLow=new Float64Array(n);let l=0,h=0,m=0;const al=1/(1+sr/(2*Math.PI*200)),ah=1/(1+sr/(2*Math.PI*3000)),am=1/(1+sr/(2*Math.PI*2500));for(let i=0;i<n;i+=1){l+=al*(x[i]-l);h+=ah*(x[i]-h);m+=am*(x[i]-m);low[i]=l;highLow[i]=x[i]-h;midLow[i]=m-l;}for(let i=0;i<n;i+=1)x[i]=low[i]*fx.eqLowPpm/PPM+midLow[i]*fx.eqMidPpm/PPM+highLow[i]*fx.eqHighPpm/PPM;x=normalizeFloat(x,.95);}if(fx.chorus){const mix=fx.chorusMixPpm/PPM,out=new Float64Array(n);for(let i=0;i<n;i+=1){const delay=(.01+.002*Math.sin(2*Math.PI*.8*i/sr))*sr,pos=i-delay,index=Math.floor(pos),frac=pos-index,wet=index>=0?x[index]*(1-frac)+(index+1<n?x[index+1]:x[index])*frac:0;out[i]=(1-mix)*x[i]+mix*wet;}x=normalizeFloat(out,.95);}if(fx.reverb){const wet=fx.reverbWetPpm/PPM,out=new Float64Array(x);for(const sec of [.0297,.0371,.0411,.0437]){const delay=Math.floor(sec*sr);let damp=0;for(let i=delay;i<n;i+=1){damp=.42*x[i-delay]+.58*damp;out[i]+=wet*damp;}}x=normalizeFloat(out,.95);}return x;}
  function onePoleInt(input,cutoff,sr){const out=new Int32Array(input.length),alpha=C.roundDiv(Q20*cutoff*6283,sr*1000+cutoff*6283);let state=0;for(let i=0;i<input.length;i+=1){state+=mulScale(alpha,input[i]-state,Q20);out[i]=state;}return out;}
  function fxStrict(input,config){let x=new Int32Array(input),n=x.length,sr=config.sampleRate,fx=config.fx;if(fx.distortion){const out=new Int32Array(n),mix=fx.distMixPpm,drive=fx.driveMilli;for(let i=0;i<n;i+=1){const driven=C.roundDiv(x[i]*drive,1000),wet=C.roundDiv(driven*Q15,Q15+Math.abs(driven));out[i]=C.roundDiv(x[i]*(PPM-mix)+wet*mix,PPM);}x=normalizeInt(out,31129);}if(fx.eq){const lo=onePoleInt(x,200,sr),hiBase=onePoleInt(x,3000,sr),midTop=onePoleInt(x,2500,sr),out=new Int32Array(n);for(let i=0;i<n;i+=1){const low=mulScale(lo[i],fx.eqLowPpm,PPM),mid=mulScale(midTop[i]-lo[i],fx.eqMidPpm,PPM),high=mulScale(x[i]-hiBase[i],fx.eqHighPpm,PPM);out[i]=low+mid+high;}x=normalizeInt(out,31129);}if(fx.chorus){const out=new Int32Array(n),mix=fx.chorusMixPpm,base=Math.floor(.01*sr),depth=Math.floor(.002*sr),inc=C.phaseIncrement(800,sr);let phase=0;for(let i=0;i<n;i+=1){const delay=base+C.roundDiv(C.strictSinQ15(phase)*depth,Q15),index=i-delay,wet=index>=0?x[index]:0;out[i]=C.roundDiv(x[i]*(PPM-mix)+wet*mix,PPM);phase=(phase+inc)>>>0;}x=normalizeInt(out,31129);}if(fx.reverb){const out=new Int32Array(x),wet=fx.reverbWetPpm;for(const us of [29700,37100,41100,43700]){const delay=Math.floor(us*sr/1000000);let damp=0;for(let i=delay;i<n;i+=1){damp=C.roundDiv(42*x[i-delay]+58*damp,100);out[i]+=mulScale(damp,wet,PPM);}}x=normalizeInt(out,31129);}return x;}
  function preview(array,size){const count=Math.min(size,array.length),out=new Float32Array(count);let max=1e-12;for(const v of array)max=Math.max(max,Math.abs(v));for(let i=0;i<count;i+=1){const start=Math.floor(i*array.length/count),end=Math.max(start+1,Math.floor((i+1)*array.length/count));let sum=0;for(let j=start;j<end;j+=1)sum+=array[j];out[i]=sum/(end-start)/max;}return out;}
  function integerSqrt(value){if(value<0n)throw new RangeError("square root of negative integer");if(value<2n)return value;let x0=value,x1=(x0+value/x0)>>1n;while(x1<x0){x0=x1;x1=(x0+value/x0)>>1n;}return x0;}
  function metrics(array,strict){
    if(strict){let maximum=0,sum=0n;for(const v of array){const absolute=Math.abs(v);maximum=Math.max(maximum,absolute);sum+=BigInt(v)*BigInt(v);}const rms=integerSqrt(sum/BigInt(array.length));return{maximum_ppm:C.roundDiv(maximum*PPM,Q15),rms_ppm:C.roundDiv(Number(rms)*PPM,Q15)};}
    let max=0,sum=0;for(const v of array){max=Math.max(max,Math.abs(v));sum+=v*v;}return{maximum_ppm:Math.round(max*1000000),rms_ppm:Math.round(Math.sqrt(sum/array.length)*1000000)};
  }
  async function render(config,options){validate(config);const ctx={signal:options&&options.signal,progress:options&&options.progress};const strict=config.mode===PA.MODES.STRICT,light=strict?await generateStrict(config,ctx):await generateFloat(config,ctx);if(light.length!==config.durationSamples)throw new Error("Rendered light length disagrees with the frozen recipe");let stages;
    if(config.presetId==="evolving-demo"){
      const sections=DEMO_SCHEDULE,absorbed=strict?new Int32Array(light.length):new Float64Array(light.length),temp=strict?new Int32Array(light.length):new Float64Array(light.length),pressure=strict?new Int32Array(light.length):new Float64Array(light.length),acoustic=strict?new Int32Array(light.length):new Float64Array(light.length);for(let s=0;s<sections.length;s+=1){const section=sections[s],a=section.startNumerator/section.startDenominator,b=section.endNumerator/section.endDenominator,mid=section.materialId,rid=section.resonatorId,power=section.laserPowerPpm,i0=Math.floor(a*light.length),i1=s===sections.length-1?light.length:Math.floor(b*light.length),part=light.slice(i0,i1),local=Object.assign({},config,{laserPowerPpm:power}),result=strict?await transformStrict(part,copyMaterial(mid),copyResonator(rid),local,ctx,[.12+s*.15,.12+(s+1)*.15]):await transformFloat(part,copyMaterial(mid),copyResonator(rid),local,ctx,[.12+s*.15,.12+(s+1)*.15]);absorbed.set(result.absorbed,i0);temp.set(result.temp,i0);pressure.set(result.pressure,i0);acoustic.set(result.acoustic,i0);const fade=Math.min(Math.floor(.4*config.sampleRate),Math.floor((i1-i0)/2));for(let j=0;j<fade;j+=1){if(i0>0)acoustic[i0+j]=strict?C.roundDiv(acoustic[i0+j]*j,fade):acoustic[i0+j]*j/fade;if(i1<light.length)acoustic[i1-1-j]=strict?C.roundDiv(acoustic[i1-1-j]*j,fade):acoustic[i1-1-j]*j/fade;}}stages={absorbed,temp,pressure,acoustic};
    } else stages=strict?await transformStrict(light,config.material,config.resonator,config,ctx):await transformFloat(light,config.material,config.resonator,config,ctx);
    const final=strict?fxStrict(stages.acoustic,config):fxFloat(stages.acoustic,config);await C.checkpoint(ctx.signal,ctx.progress,.92,"post-processing complete");const traces={light:preview(light,2048),temperature:preview(stages.temp,2048),pressure:preview(stages.pressure,2048),acoustic:preview(final,2048)},stageMetrics={light:metrics(light,strict),temperature:metrics(stages.temp,strict),pressure:metrics(stages.pressure,strict),acoustic:metrics(final,strict)};await C.checkpoint(ctx.signal,ctx.progress,.96,"stage receipts ready");return{strict,signal:final,traces,stageMetrics,sampleRate:config.sampleRate};
  }

  PA.Model=Object.freeze({MATERIALS,RESONATORS,DEMO_SCHEDULE,PRESETS,copyMaterial,copyResonator,validate,render,quantities:Object.freeze({Q15,Q20,PPM})});
})(window);
