(function (root) {
  "use strict";
  const PA=root.PHOTOACOUSTIC,C=PA.Core,A=PA.Audio,M=PA.Model;
  const DOMAINS=Object.freeze({recipe:"SPECTRAL/PHOTOACOUSTIC/RECIPE/v1",fingerprint:"SPECTRAL/PHOTOACOUSTIC/FINGERPRINT/v1",contract:"SPECTRAL/PHOTOACOUSTIC/CONTRACT/v1",manifest:"SPECTRAL/PHOTOACOUSTIC/MANIFEST-CORE/v1",stage:"SPECTRAL/PHOTOACOUSTIC/STAGE/v1"});
  const PROFILES=Object.freeze({
    archive:Object.freeze({id:"archive",name:"Archive",sampleRate:44100,channels:1,ceilingMilliDb:-700,ceilingQ15:30230}),
    "suno-seed":Object.freeze({id:"suno-seed",name:"Suno Seed",sampleRate:48000,channels:2,ceilingMilliDb:-6000,ceilingQ15:16422}),
    "laboratory-hot":Object.freeze({id:"laboratory-hot",name:"Laboratory Hot",sampleRate:44100,channels:1,ceilingMilliDb:-100,ceilingQ15:32392})
  });
  function deepFreeze(value){if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const key of Object.keys(value))deepFreeze(value[key]);}return value;}
  function detached(value){return JSON.parse(C.stableStringify(value));}
  function normalizedGenerator(generator){switch(generator.type){case"fibonacci":return{type:generator.type,pulse1Milli:generator.pulse1Milli,pulse2Milli:generator.pulse2Milli,pulseWidthUs:generator.pulseWidthUs,fibDepth:generator.fibDepth,pulseShape:generator.pulseShape};case"dual-pulse":return{type:generator.type,pulse1Milli:generator.pulse1Milli,pulse2Milli:generator.pulse2Milli,pulseWidthUs:generator.pulseWidthUs,pulseShape:generator.pulseShape};case"tone":return{type:generator.type,toneMilli:generator.toneMilli};case"industrial":return{type:generator.type,bpmMilli:generator.bpmMilli};case"wav":return{type:generator.type,lightBiasPpm:500000,modulationDepthPpm:450000};case"melody":case"chord-chop":return{type:generator.type};default:throw new Error("Unsupported light generator");}}
  function expandedGenerator(generator){return{type:generator.type,bpmMilli:generator.bpmMilli===undefined?90000:generator.bpmMilli,toneMilli:generator.toneMilli===undefined?220000:generator.toneMilli,pulse1Milli:generator.pulse1Milli===undefined?8000:generator.pulse1Milli,pulse2Milli:generator.pulse2Milli===undefined?12500:generator.pulse2Milli,pulseWidthUs:generator.pulseWidthUs===undefined?3000:generator.pulseWidthUs,fibDepth:generator.fibDepth===undefined?8:generator.fibDepth,pulseShape:generator.pulseShape||"gaussian"};}
  function normalizedFx(fx){const out={distortion:fx.distortion,eq:fx.eq,chorus:fx.chorus,reverb:fx.reverb};if(fx.distortion){out.driveMilli=fx.driveMilli;out.distMixPpm=fx.distMixPpm;}if(fx.eq){out.eqLowPpm=fx.eqLowPpm;out.eqMidPpm=fx.eqMidPpm;out.eqHighPpm=fx.eqHighPpm;}if(fx.chorus)out.chorusMixPpm=fx.chorusMixPpm;if(fx.reverb)out.reverbWetPpm=fx.reverbWetPpm;return out;}
  function expandedFx(fx){return{distortion:fx.distortion,driveMilli:fx.driveMilli===undefined?2200:fx.driveMilli,distMixPpm:fx.distMixPpm===undefined?400000:fx.distMixPpm,eq:fx.eq,eqLowPpm:fx.eqLowPpm===undefined?1000000:fx.eqLowPpm,eqMidPpm:fx.eqMidPpm===undefined?1000000:fx.eqMidPpm,eqHighPpm:fx.eqHighPpm===undefined?1000000:fx.eqHighPpm,chorus:fx.chorus,chorusMixPpm:fx.chorusMixPpm===undefined?250000:fx.chorusMixPpm,reverb:fx.reverb,reverbWetPpm:fx.reverbWetPpm===undefined?350000:fx.reverbWetPpm};}
  function expandedDemoSchedule(){return M.DEMO_SCHEDULE.map(section=>({start_numerator:section.startNumerator,start_denominator:section.startDenominator,end_numerator:section.endNumerator,end_denominator:section.endDenominator,laser_power_ppm:section.laserPowerPpm,material:M.copyMaterial(section.materialId),resonator:M.copyResonator(section.resonatorId)}));}
  function sourceIdentity(source){return source?{adapter:"canonical-riff-wav/v1",sha256:source.hash,byte_length:source.byteLength,wav:{format:source.format,channels:source.channels,sample_rate:source.sampleRate,bits_per_sample:source.bitsPerSample,frames:source.frames,strict_compatible:source.strictCompatible}}:null;}
  function recipeFromConfig(config){
    const demo=config.presetId==="evolving-demo",recipe={schema:"spectral-photoacoustic-recipe/v1",app_version:PA.VERSION,engine_version:PA.ENGINE_VERSION,algorithms:{canonical_json:"safe-integer-lexical/v1",strict_kernel:"q15-pa-svf-bhaskara/v1",replay_kernel:"float64-browser-pa-iirpeak/v1",wav_parser:"riff-manual/v1",wav_writer:"pcm16-le/v1",resampler:"linear-explicit/v1",zip:"store-fixed-epoch/v1"},determinism_mode:config.mode,seed:String(config.seed),mutation_index:config.mutation,preset_id:config.presetId,sample_rate:config.sampleRate,duration_samples:config.durationSamples,profile:config.profile,generator:normalizedGenerator(config.generator),pressure_derivative:config.derivative,fx:normalizedFx(config.fx),source:sourceIdentity(config.source),claim_boundary:"Simplified audio-rate artistic model; not a calibrated physical, biomedical, or engineering prediction."};
    if(demo)recipe.evolving_sections=expandedDemoSchedule();else{recipe.material=config.material;recipe.resonator=config.resonator;recipe.laser_power_ppm=config.laserPowerPpm;}
    if(config.mode===PA.MODES.REPLAY)recipe.runtime=C.runtimeFingerprint();return deepFreeze(detached(recipe));
  }
  function configFromRecipe(recipe,source){const demo=recipe.preset_id==="evolving-demo";return{mode:recipe.determinism_mode,seed:recipe.seed,mutation:recipe.mutation_index,presetId:recipe.preset_id,sampleRate:recipe.sample_rate,durationSamples:recipe.duration_samples,profile:recipe.profile,generator:expandedGenerator(recipe.generator),material:demo?M.copyMaterial("soot"):detached(recipe.material),resonator:demo?M.copyResonator("jar"):detached(recipe.resonator),laserPowerPpm:demo?1000000:recipe.laser_power_ppm,derivative:recipe.pressure_derivative,fx:expandedFx(recipe.fx),source:source||null};}
  function normalizeSignal(result,profile){
    const n=result.signal.length,fade=Math.min(Math.floor(result.sampleRate*.01),Math.floor(n/2));let mono;
    if(result.strict){let maximum=1;for(const value of result.signal)maximum=Math.max(maximum,Math.abs(value));mono=new Int16Array(n);for(let i=0;i<n;i+=1){let value=C.roundDiv(result.signal[i]*profile.ceilingQ15,maximum);if(i<fade)value=C.roundDiv(value*i,fade);if(i>=n-fade)value=C.roundDiv(value*(n-1-i),fade);mono[i]=C.clampInt(value,-32768,32767);}}
    else{let maximum=1e-15;for(const value of result.signal)maximum=Math.max(maximum,Math.abs(value));const gain=profile.ceilingQ15/32767/maximum;mono=new Int16Array(n);for(let i=0;i<n;i+=1){let value=result.signal[i]*gain;if(i<fade)value*=i/fade;if(i>=n-fade)value*=(n-1-i)/fade;mono[i]=A.quantizePcm16(value);}}
    const interleaved=new Int16Array(n*profile.channels);for(let i=0;i<n;i+=1)for(let channel=0;channel<profile.channels;channel+=1)interleaved[i*profile.channels+channel]=mono[i];return{mono,interleaved};
  }
  function integerSqrt(value){if(value<2n)return value;let x=value,y=(x+value/x)>>1n;while(y<x){x=y;y=(x+value/x)>>1n;}return x;}
  async function fingerprint(mono,pcm,wav,profile,options){
    let peak=0,sum=0n,dc=0n,zero=0,clips=0,previous=mono[0]||0;const scanChunk=262144;for(let base=0;base<mono.length;base+=scanChunk){const end=Math.min(mono.length,base+scanChunk);for(let i=base;i<end;i+=1){const value=mono[i],abs=Math.abs(value);peak=Math.max(peak,abs);sum+=BigInt(value)*BigInt(value);dc+=BigInt(value);if(abs>=32767)clips+=1;if((value<0&&previous>=0)||(value>=0&&previous<0))zero+=1;previous=value;}if(end<mono.length)await C.checkpoint(options&&options.signal,options&&options.progress,.972+.006*end/mono.length,"fingerprinting PCM");}
    const rms=Number(integerSqrt(sum/BigInt(Math.max(1,mono.length)))),chunkSize=65536,chunks=[];for(let offset=0;offset<pcm.length;offset+=chunkSize){chunks.push(C.sha256Hex(pcm.slice(offset,Math.min(offset+chunkSize,pcm.length))));if(chunks.length%16===0)await C.checkpoint(options&&options.signal,options&&options.progress,.979,"hashing PCM chunks");}
    const bins=Math.min(64,mono.length),envelope=[];for(let bin=0;bin<bins;bin+=1){const start=Math.floor(bin*mono.length/bins),end=Math.min(mono.length,Math.max(start+1,Math.floor((bin+1)*mono.length/bins)));let local=0n;for(let i=start;i<end;i+=1)local+=BigInt(mono[i])*BigInt(mono[i]);envelope.push(Number(integerSqrt(local/BigInt(end-start))));if(bin%8===7)await C.checkpoint(options&&options.signal,options&&options.progress,.98+.004*(bin+1)/bins,"building RMS envelope");}
    return{schema:"spectral-photoacoustic-fingerprint/v1",sample_rate:profile.sampleRate,channels:profile.channels,frames:mono.length,peak_q15:peak,rms_q15:rms,dc_offset_ppm:Number(dc*1000000n/BigInt(Math.max(1,mono.length)*32768)),zero_crossings:zero,clipping_samples:clips,pcm_sha256:C.sha256Hex(pcm),wav_sha256:C.sha256Hex(wav),pcm_chunk_size_bytes:chunkSize,pcm_chunk_sha256:chunks,repeated_exact_chunk:chunks.length!==new Set(chunks).size,rms_envelope_q15:envelope,rms_envelope_sha256:C.sha256Hex(C.utf8(envelope.join(",")))};
  }
  function readiness(fp,profile){const findings=[];if(fp.clipping_samples)findings.push({level:"fail",code:"clipping",detail:fp.clipping_samples+" full-scale samples"});if(Math.abs(fp.dc_offset_ppm)>10000)findings.push({level:"warn",code:"dc_offset",detail:fp.dc_offset_ppm+" ppm"});if(fp.peak_q15<4096)findings.push({level:"warn",code:"low_peak",detail:"Very low output peak"});if(fp.repeated_exact_chunk)findings.push({level:"info",code:"exact_repetition",detail:"Repeated exact PCM chunks observed"});if(!findings.length)findings.push({level:"pass",code:"technical_checks",detail:"No clipping, excessive DC, low peak, or exact chunk repetition observed"});return{schema:"spectral-photoacoustic-readiness/v1",profile_id:profile.id,advisory_only:true,guarantees_external_acceptance:false,findings};}
  function stageReceipt(result,recipe,recipeHash){return{schema:"spectral-photoacoustic-stage-receipt/v1",recipe_sha256:recipeHash,model_chain:["light_intensity","optical_absorption","thermal_rc","pressure_conversion","parallel_cavity_modes","post_fx","pcm16_quantization"],backend:result.strict?"fixed-point-q15":"float64-runtime-scoped",pressure_derivative:recipe.pressure_derivative,expanded_material:recipe.material||null,expanded_resonator:recipe.resonator||null,evolving_sections:recipe.evolving_sections||null,stage_metrics:result.stageMetrics,claim_boundary:recipe.claim_boundary};}
  function originText(recipe,hashes){return[
    "SPECTRAL PHOTOACOUSTIC LABORATORY 2.0 — ORIGIN RECEIPT","",`Engine: ${recipe.engine_version}`,`Mode: ${recipe.determinism_mode}`,`Preset: ${recipe.preset_id}`,`Recipe SHA-256: ${hashes.recipe}`,`PCM SHA-256: ${hashes.pcm}`,`WAV SHA-256: ${hashes.wav}`,`Fingerprint SHA-256: ${hashes.fingerprint}`,`Contract SHA-256: ${hashes.contract}`,"","MODEL BOUNDARY",recipe.claim_boundary,"","Generated locally in the browser. WebAudio was used only for playback and did not supply identity-bearing samples.","Licensed under the MIT License. Copyright (c) 2026 Trent Slade (QSOL-IMC).",""
  ].join("\n");}
  function bytesOf(value){return C.utf8(C.prettyStable(value));}
  async function render(config,options){
    const profile=PROFILES[config.profile];if(!profile)throw new Error("Unknown export profile");if(config.sampleRate!==profile.sampleRate)throw new Error("Configuration sample rate does not match export profile");
    const recipe=recipeFromConfig(config),recipeHash=C.domainHash(DOMAINS.recipe,recipe),modelResult=await M.render(config,options||{});await C.checkpoint(options&&options.signal,options&&options.progress,.962,"normalizing output");const normalized=normalizeSignal(modelResult,profile);await C.checkpoint(options&&options.signal,options&&options.progress,.968,"packing canonical WAV");const encoded=A.encodePcm16(normalized.interleaved,profile.sampleRate,profile.channels),pcmHash=C.sha256Hex(encoded.pcmBytes),wavHash=C.sha256Hex(encoded.wavBytes);await C.checkpoint(options&&options.signal,options&&options.progress,.972,"fingerprinting output");const fp=await fingerprint(normalized.mono,encoded.pcmBytes,encoded.wavBytes,profile,options||{}),fingerprintHash=C.domainHash(DOMAINS.fingerprint,fp),stage=stageReceipt(modelResult,recipe,recipeHash),stageHash=C.domainHash(DOMAINS.stage,stage),ready=readiness(fp,profile);await C.checkpoint(options&&options.signal,options&&options.progress,.988,"sealing observation contract");
    const contractCore={schema:"spectral-photoacoustic-contract/v1",recipe_sha256:recipeHash,pcm_sha256:pcmHash,wav_sha256:wavHash,fingerprint_sha256:fingerprintHash,stage_receipt_sha256:stageHash,backend:modelResult.strict?"q15-fixed-point":"float64-replay-safe",sample_format:"signed-pcm16-le",sample_rate:profile.sampleRate,channels:profile.channels,frames:normalized.mono.length,replay_requirement:modelResult.strict?"same normalized recipe and source bytes":"same normalized recipe, source bytes, and recorded runtime"},contractHash=C.domainHash(DOMAINS.contract,contractCore),contract=Object.assign({},contractCore,{contract_sha256:null});contract.contract_sha256=contractHash;
    const hashes={recipe:recipeHash,pcm:pcmHash,wav:wavHash,fingerprint:fingerprintHash,contract:contractHash},origin=originText(recipe,hashes),originBytes=C.utf8(origin),fpBytes=bytesOf(fp),stageBytes=bytesOf(stage),readyBytes=bytesOf(ready),derivation={schema:"spectral-photoacoustic-derivation/v1",seed:{recipe_sha256:recipeHash,contract_sha256:contractHash,wav_sha256:wavHash},derivatives:[]},derivationBytes=bytesOf(derivation);
    const manifestCore={schema:PA.SCHEMA_VERSION,recipe,recipe_sha256:recipeHash,contract,artifacts:{audio_wav:{filename:"audio.wav",sha256:wavHash,bytes:encoded.wavBytes.length},derivation_graph_json:{filename:"derivation_graph.json",sha256:C.sha256Hex(derivationBytes),bytes:derivationBytes.length},fingerprint_json:{filename:"fingerprint.json",sha256:C.sha256Hex(fpBytes),bytes:fpBytes.length},stage_receipt_json:{filename:"stage_receipt.json",sha256:C.sha256Hex(stageBytes),bytes:stageBytes.length},upload_readiness_json:{filename:"upload_readiness.json",sha256:C.sha256Hex(readyBytes),bytes:readyBytes.length},readme_origin_txt:{filename:"README_ORIGIN.txt",sha256:C.sha256Hex(originBytes),bytes:originBytes.length}}},manifestCoreHash=C.domainHash(DOMAINS.manifest,manifestCore),manifest=Object.assign({},manifestCore,{manifest_core_sha256:manifestCoreHash}),manifestBytes=bytesOf(manifest);await C.checkpoint(options&&options.signal,options&&options.progress,.995,"packaging deterministic bundle");const bundle=A.zip([{name:"audio.wav",bytes:encoded.wavBytes},{name:"derivation_graph.json",bytes:derivationBytes},{name:"fingerprint.json",bytes:fpBytes},{name:"manifest.json",bytes:manifestBytes},{name:"README_ORIGIN.txt",bytes:originBytes},{name:"stage_receipt.json",bytes:stageBytes},{name:"upload_readiness.json",bytes:readyBytes}]);
    if(options&&options.progress)options.progress(1,"render contract sealed");
    return{id:contractHash.slice(0,16),recipe,recipeHash,pcmHash,wavHash,fingerprint:fp,fingerprintHash,stageReceipt:stage,stageHash,readiness:ready,derivation,contract,contractHash,manifest,manifestCoreHash,wavBytes:encoded.wavBytes,pcmBytes:encoded.pcmBytes,monoPcm:normalized.mono,bundleBytes:bundle,originText:origin,traces:modelResult.traces,profile,artifacts:{"audio.wav":{bytes:encoded.wavBytes,type:"audio/wav"},"manifest.json":{bytes:manifestBytes,type:"application/json"},"fingerprint.json":{bytes:fpBytes,type:"application/json"},"stage_receipt.json":{bytes:stageBytes,type:"application/json"},"derivation_graph.json":{bytes:derivationBytes,type:"application/json"},"upload_readiness.json":{bytes:readyBytes,type:"application/json"},"README_ORIGIN.txt":{bytes:originBytes,type:"text/plain"},"photoacoustic_provenance.zip":{bytes:bundle,type:"application/zip"}}};
  }
  function verifyManifest(manifest){if(!manifest||manifest.schema!==PA.SCHEMA_VERSION)throw new Error("Unsupported photoacoustic manifest schema");if(!manifest.recipe||manifest.recipe.schema!=="spectral-photoacoustic-recipe/v1"||manifest.recipe.app_version!==PA.VERSION||manifest.recipe.engine_version!==PA.ENGINE_VERSION)throw new Error("Manifest requires an unavailable application or engine version");if(!M.PRESETS[manifest.recipe.preset_id])throw new Error("Manifest contains an unsupported preset ID");const supplied=manifest.manifest_core_sha256,core=Object.assign({},manifest);delete core.manifest_core_sha256;if(C.domainHash(DOMAINS.manifest,core)!==supplied)throw new Error("Manifest core hash mismatch");if(C.domainHash(DOMAINS.recipe,manifest.recipe)!==manifest.recipe_sha256)throw new Error("Recipe hash mismatch");if(manifest.contract.recipe_sha256!==manifest.recipe_sha256)throw new Error("Contract is bound to a different recipe");const contractCore=Object.assign({},manifest.contract);delete contractCore.contract_sha256;if(C.domainHash(DOMAINS.contract,contractCore)!==manifest.contract.contract_sha256)throw new Error("Contract hash mismatch");return true;}
  async function replay(manifest,source,options){verifyManifest(manifest);if(manifest.recipe.source){if(!source)throw new Error("Replay requires the original WAV source");if(source.hash!==manifest.recipe.source.sha256||source.byteLength!==manifest.recipe.source.byte_length)throw new Error("Replay source hash or length does not match");}if(manifest.recipe.determinism_mode===PA.MODES.REPLAY&&manifest.recipe.runtime.hash!==C.runtimeFingerprint().hash)throw new Error("Replay Safe manifest belongs to a different recorded runtime");const config=configFromRecipe(manifest.recipe,source),job=await render(config,options);if(job.wavHash!==manifest.contract.wav_sha256)throw new Error("Replayed WAV hash mismatch");if(job.contractHash!==manifest.contract.contract_sha256)throw new Error("Replayed contract hash mismatch");if(job.manifestCoreHash!==manifest.manifest_core_sha256)throw new Error("Replayed manifest hash mismatch");return job;}

  PA.Provenance=Object.freeze({DOMAINS,PROFILES,recipeFromConfig,configFromRecipe,render,verifyManifest,replay});
})(window);
