(function (root) {
  "use strict";
  const PA=root.PHOTOACOUSTIC;
  const DB_NAME="spectral-photoacoustic-v2",STORE="jobs",VERSION=1,LIMIT=24;
  let db=null,supported=true,memory=[];
  function requestPromise(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("IndexedDB request failed"));});}
  async function init(){if(!root.indexedDB){supported=false;return{supported:false,reason:"IndexedDB unavailable"};}try{db=await new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,VERSION);request.onupgradeneeded=()=>{const next=request.result;if(!next.objectStoreNames.contains(STORE)){const store=next.createObjectStore(STORE,{keyPath:"id"});store.createIndex("savedAt","savedAt");}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error("IndexedDB blocked"));});return{supported:true};}catch(error){supported=false;db=null;return{supported:false,reason:String(error.message||error)};}}
  function compact(job){return{id:job.id,savedAt:Date.now(),presetId:job.recipe.preset_id,mode:job.recipe.determinism_mode,profileId:job.profile.id,frames:job.fingerprint.frames,sampleRate:job.profile.sampleRate,wavHash:job.wavHash,contractHash:job.contractHash,wavBytes:job.wavBytes.buffer.slice(job.wavBytes.byteOffset,job.wavBytes.byteOffset+job.wavBytes.byteLength),bundleBytes:job.bundleBytes.buffer.slice(job.bundleBytes.byteOffset,job.bundleBytes.byteOffset+job.bundleBytes.byteLength),manifest:job.manifest,fingerprint:job.fingerprint,originText:job.originText};}
  async function save(job){const record=compact(job);if(!supported||!db){memory=memory.filter(value=>value.id!==record.id);memory.unshift(record);memory=memory.slice(0,LIMIT);return record;}const tx=db.transaction(STORE,"readwrite"),store=tx.objectStore(STORE);store.put(record);await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error("IndexedDB write aborted"));});const all=await list();if(all.length>LIMIT){const remove=db.transaction(STORE,"readwrite"),target=remove.objectStore(STORE);for(const old of all.slice(LIMIT))target.delete(old.id);await new Promise((resolve,reject)=>{remove.oncomplete=resolve;remove.onerror=()=>reject(remove.error);});}return record;}
  async function list(){if(!supported||!db)return memory.slice().sort((a,b)=>b.savedAt-a.savedAt);const tx=db.transaction(STORE,"readonly"),values=await requestPromise(tx.objectStore(STORE).getAll());return values.sort((a,b)=>b.savedAt-a.savedAt);}
  async function get(id){if(!supported||!db)return memory.find(value=>value.id===id)||null;return requestPromise(db.transaction(STORE,"readonly").objectStore(STORE).get(id));}
  async function clear(){memory=[];if(!supported||!db)return;const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).clear();await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
  async function selfTest(){if(!supported||!db)return{supported:false,passed:false};const id="__pa_self_test__",payload={id,savedAt:0,wavBytes:new Uint8Array([1,2,3,4]).buffer};try{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(payload);await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});const read=await get(id),remove=db.transaction(STORE,"readwrite");remove.objectStore(STORE).delete(id);await new Promise(resolve=>{remove.oncomplete=resolve;remove.onerror=resolve;});return{supported:true,passed:!!read&&new Uint8Array(read.wavBytes)[3]===4};}catch(error){return{supported:true,passed:false,reason:String(error.message||error)};}}
  PA.Storage=Object.freeze({init,save,list,get,clear,selfTest,isSupported:()=>supported&&!!db});
})(window);
