(function(root){
  "use strict";
  const PA=root.PHOTOACOUSTIC,C=PA.Core,M=PA.Model,P=PA.Provenance,A=PA.Audio,V=PA.Visuals,S=PA.Storage;
  const $=id=>document.getElementById(id);let source=null,currentJob=null,audioUrl=null,activeStage="light",abortController=null,presetFx=null,isApplying=false,controlSnapshot=[];
  const captions={light:"Light intensity modulation entering the absorber.",temperature:"Thermal RC response after steady-state DC removal.",pressure:"Direct and sample-gradient thermal expansion mapped to pressure.",acoustic:"Cavity response and post-processing before PCM16 export."};
  const presetDuration={"industrial-fib":"20","soot-music":"15.6","resonant-gas":"20","ultrasonic-edge":"20","drone-dark":"20","evolving-demo":"45","pulse-lab":"20","tone-lab":"20","wav-through":"20"};
  function setStatus(text,error){$("render-status").textContent=text;$("render-status").style.color=error?"var(--red)":"";}
  function number(id){const value=$(id).value;if(!String(value).trim())throw new Error("Missing value: "+id);return value;}
  function parseList(id,scale,min,max){const parts=$(id).value.split(",").map(value=>value.trim()).filter(Boolean);if(!parts.length)throw new Error(id+" requires at least one number");return parts.map(value=>{const normalized=C.decimalToScaled(value,scale);if(normalized<min||normalized>max)throw new Error(id+" contains an out-of-range value");return normalized;});}
  function profile(){return P.PROFILES[$("profile").value];}
  function populateRegistry(){for(const value of Object.values(M.MATERIALS))$("material").add(new Option(value.name,value.id));for(const value of Object.values(M.RESONATORS))$("resonator").add(new Option(value.name,value.id));}
  function loadMaterial(id){const value=M.MATERIALS[id];$("absorption").value=(value.absorptionPpm/1e6).toString();$("thermal-tau").value=(value.tauUs/1000).toString();$("gruneisen").value=(value.gruneisenPpm/1e6).toString();$("expansion").value=(value.expansionPpm/1e6).toString();$("nonlinearity").value=(value.nonlinearityPpm/1e6).toString();$("material-note").textContent=value.comment;}
  function loadResonator(id){const value=M.RESONATORS[id];$("resonances").value=value.frequenciesMilli.map(v=>v/1000).join(", ");$("q-factors").value=value.qMilli.map(v=>v/1000).join(", ");$("resonator-gain").value=(value.gainPpm/1e6).toString();$("resonator-note").textContent=value.comment;}
  function showField(id,show){const field=$(id).closest(".field");if(field)field.classList.toggle("hidden",!show);}
  function updateGeneratorVisibility(type){const visible={duration:true,bpm:type==="industrial",tone:type==="tone",pulse1:["fibonacci","dual-pulse"].includes(type),pulse2:["fibonacci","dual-pulse"].includes(type),width:["fibonacci","dual-pulse"].includes(type),fib:type==="fibonacci",shape:["fibonacci","dual-pulse"].includes(type)};showField("duration",visible.duration);showField("bpm",visible.bpm);showField("tone-frequency",visible.tone);showField("pulse-rate",visible.pulse1);showField("pulse-rate-2",visible.pulse2);showField("pulse-width",visible.width);showField("fib-depth",visible.fib);showField("pulse-shape",visible.shape);}
  function demoControlState(demo){for(const id of ["material","absorption","thermal-tau","gruneisen","expansion","nonlinearity","laser-power","derivative","resonator","resonances","q-factors","resonator-gain"])$(id).disabled=demo;if(demo){$("material-note").textContent="Fixed four-stage schedule: soot/jar → charcoal/pipe → ethene/H-cell → CS/PDMS/open.";$("resonator-note").textContent="The complete expanded schedule is recorded in the recipe and stage receipt.";}}
  function applyPreset(id){const value=M.PRESETS[id];if(!value)return;isApplying=true;$("preset-description").textContent=value.description;$("material").value=value.material;loadMaterial(value.material);$("resonator").value=value.resonator;loadResonator(value.resonator);$("laser-power").value=(value.laserPowerPpm/1e6).toString();$("derivative").checked=value.derivative;$("bpm").value=(value.bpmMilli/1000).toString();$("tone-frequency").value="220";$("pulse-rate").value=(value.pulse1Milli/1000).toString();$("pulse-rate-2").value=(value.pulse2Milli/1000).toString();$("pulse-width").value=(value.pulseWidthUs/1000).toString();$("fib-depth").value=value.fibDepth;$("pulse-shape").value=value.shape;$("duration").value=presetDuration[id];presetFx=Object.assign({},value.fx);$("fx-distortion").checked=value.fx.distortion;$("drive").value=(value.fx.driveMilli/1000).toString();$("dist-mix").value=(value.fx.distMixPpm/1e6).toString();$("fx-eq").checked=value.fx.eq;$("fx-chorus").checked=value.fx.chorus;$("chorus-mix").value=(value.fx.chorusMixPpm/1e6).toString();$("fx-reverb").checked=value.fx.reverb;$("reverb-wet").value=(value.fx.reverbWetPpm/1e6).toString();$("wav-source-wrap").classList.toggle("hidden",id!=="wav-through");updateGeneratorVisibility(value.generator);demoControlState(id==="evolving-demo");$("duration").disabled=id==="wav-through"&&!!source;isApplying=false;}
  function modeNote(){const strict=$("mode").value===PA.MODES.STRICT;$("mode-note").textContent=strict?"Integer-only signal ABI for byte-stable PCM/WAV identity. This is a versioned fixed-point redesign, not NumPy byte parity.":"Browser Float64 reinterpretation with SciPy-compatible cavity peak coefficients and the runtime bound into recipe identity.";}
  function markStale(){if(!currentJob||isApplying||abortController)return;$("downloads").classList.add("stale");if(!$("downloads").querySelector(".stale-banner")){const note=document.createElement("p");note.className="stale-banner";note.textContent="OUTPUT STALE · artifacts below belong to the previous sealed recipe. Render current settings to replace them.";$("downloads").prepend(note);}setStatus("OUTPUT STALE · render current settings before treating controls and artifacts as one recipe");$("render-time").textContent="PRIOR ARTIFACTS";}
  function lockControls(locked){const controls=Array.from(document.querySelectorAll(".control-rack input, .control-rack select, #source-file, #manifest-file, #reset"));if(locked){controlSnapshot=controls.map(control=>[control,control.disabled]);for(const [control] of controlSnapshot)control.disabled=true;}else{for(const [control,disabled] of controlSnapshot)control.disabled=disabled;controlSnapshot=[];}}
  function setNumeric(id,value,scale){$(id).value=(value/scale).toString();}
  function applyRecipeToUI(recipe){const config=P.configFromRecipe(recipe,recipe.source?source:null);isApplying=true;$("mode").value=config.mode;$("seed").value=config.seed;$("mutation").value=config.mutation;$("profile").value=config.profile;$("preset").value=config.presetId;applyPreset(config.presetId);$("duration").value=(config.durationSamples/config.sampleRate).toFixed(6).replace(/0+$/,"").replace(/\.$/,"");setNumeric("bpm",config.generator.bpmMilli,1000);setNumeric("tone-frequency",config.generator.toneMilli,1000);setNumeric("pulse-rate",config.generator.pulse1Milli,1000);setNumeric("pulse-rate-2",config.generator.pulse2Milli,1000);setNumeric("pulse-width",config.generator.pulseWidthUs,1000);$("fib-depth").value=config.generator.fibDepth;$("pulse-shape").value=config.generator.pulseShape;if(config.presetId!=="evolving-demo"){$("material").value=config.material.id;setNumeric("absorption",config.material.absorptionPpm,1000000);setNumeric("thermal-tau",config.material.tauUs,1000);setNumeric("gruneisen",config.material.gruneisenPpm,1000000);setNumeric("expansion",config.material.expansionPpm,1000000);setNumeric("nonlinearity",config.material.nonlinearityPpm,1000000);$("resonator").value=config.resonator.id;$("resonances").value=config.resonator.frequenciesMilli.map(value=>value/1000).join(", ");$("q-factors").value=config.resonator.qMilli.map(value=>value/1000).join(", ");setNumeric("resonator-gain",config.resonator.gainPpm,1000000);setNumeric("laser-power",config.laserPowerPpm,1000000);$("derivative").checked=config.derivative;}presetFx=Object.assign({},config.fx);$("fx-distortion").checked=config.fx.distortion;setNumeric("drive",config.fx.driveMilli,1000);setNumeric("dist-mix",config.fx.distMixPpm,1000000);$("fx-eq").checked=config.fx.eq;$("fx-chorus").checked=config.fx.chorus;setNumeric("chorus-mix",config.fx.chorusMixPpm,1000000);$("fx-reverb").checked=config.fx.reverb;setNumeric("reverb-wet",config.fx.reverbWetPpm,1000000);updateGeneratorVisibility(config.generator.type);modeNote();isApplying=false;}
  function buildConfig(){const p=profile(),preset=M.PRESETS[$("preset").value],generatorType=preset.generator;let durationSamples;if(generatorType==="wav"){if(!source)throw new Error("Load a local WAV before rendering");durationSamples=Math.max(2,Math.round(source.frames*p.sampleRate/source.sampleRate));}else durationSamples=Math.floor(C.decimalToScaled(number("duration"),1000)*p.sampleRate/1000);const frequencies=parseList("resonances",1000,1,p.sampleRate*500-1),qs=parseList("q-factors",1000,100,100000);if(frequencies.length!==qs.length)throw new Error("Resonance and Q lists must have equal lengths");const fxBase=presetFx||preset.fx;return{mode:$("mode").value,seed:$("seed").value,mutation:C.clampInt(Number(number("mutation")),0,2147483647),presetId:preset.id,profile:p.id,sampleRate:p.sampleRate,durationSamples,generator:{type:generatorType,bpmMilli:C.milli(number("bpm")),toneMilli:C.milli(number("tone-frequency")),pulse1Milli:C.milli(number("pulse-rate")),pulse2Milli:C.milli(number("pulse-rate-2")),pulseWidthUs:C.decimalToScaled(number("pulse-width"),1000),fibDepth:C.clampInt(Number(number("fib-depth")),2,16),pulseShape:$("pulse-shape").value},material:{id:$("material").value,absorptionPpm:C.ppm(number("absorption")),tauUs:C.decimalToScaled(number("thermal-tau"),1000),gruneisenPpm:C.ppm(number("gruneisen")),expansionPpm:C.ppm(number("expansion")),nonlinearityPpm:C.ppm(number("nonlinearity"))},resonator:{id:$("resonator").value,frequenciesMilli:frequencies,qMilli:qs,gainPpm:C.ppm(number("resonator-gain"))},laserPowerPpm:C.ppm(number("laser-power")),derivative:$("derivative").checked,fx:{distortion:$("fx-distortion").checked,driveMilli:C.milli(number("drive")),distMixPpm:C.ppm(number("dist-mix")),eq:$("fx-eq").checked,chorus:$("fx-chorus").checked,chorusMixPpm:C.ppm(number("chorus-mix")),reverb:$("fx-reverb").checked,reverbWetPpm:C.ppm(number("reverb-wet")),eqLowPpm:fxBase.eqLowPpm,eqMidPpm:fxBase.eqMidPpm,eqHighPpm:fxBase.eqHighPpm},source:generatorType==="wav"?source:null};}
  async function loadSource(file){if(!file)return;if(file.size>128*1024*1024)throw new Error("WAV exceeds the 128 MiB local safety limit");const bytes=new Uint8Array(await file.arrayBuffer()),metadata=A.parse(bytes,{decode:false}),targetRate=profile().sampleRate,targetFrames=Math.max(2,Math.round(metadata.frames*targetRate/metadata.sampleRate));if(targetFrames>targetRate*120)throw new Error("WAV would exceed the 120-second render limit");const decoded=A.parse(bytes);source=Object.assign(decoded,{name:file.name,byteLength:bytes.length,hash:C.sha256Hex(bytes),bytes});$("source-summary").textContent=`${file.name} · ${decoded.channels} ch · ${decoded.bitsPerSample}-bit ${decoded.format.toUpperCase()} · ${decoded.sampleRate} Hz · ${decoded.duration.toFixed(3)} s · ${source.hash.slice(0,16)}…`;$("duration").value=(targetFrames/targetRate).toFixed(3);$("duration").disabled=$("preset").value==="wav-through";markStale();}
  function db(value){return value>0?(20*Math.log10(value)).toFixed(2):"−∞";}
  function time(seconds){if(!Number.isFinite(seconds))seconds=0;const minutes=Math.floor(seconds/60),rest=seconds-minutes*60;return String(minutes).padStart(2,"0")+":"+rest.toFixed(3).padStart(6,"0");}
  function updateVisuals(job){V.waveform($("waveform"),job.monoPcm,job.profile.sampleRate);V.spectrogram($("spectrogram"),job.monoPcm,job.profile.sampleRate,$("frequency-scale").value);V.trace($("stage-trace"),job.traces[activeStage],activeStage.toUpperCase());}
  function updateMetrics(job){const peak=job.fingerprint.peak_q15/32768,rms=job.fingerprint.rms_q15/32768;$("metric-peak").textContent=db(peak);$("metric-rms").textContent=db(rms);$("metric-duration").textContent=(job.fingerprint.frames/job.profile.sampleRate).toFixed(3);$("metric-hash").textContent=job.wavHash.slice(0,18)+"…";$("metric-hash").title=job.wavHash;$("metric-mode").textContent=job.recipe.determinism_mode;const values=[["Recipe",job.recipeHash],["PCM payload",job.pcmHash],["Fingerprint",job.fingerprintHash],["Contract",job.contractHash]];$("contract-list").innerHTML=values.map(([name,hash])=>`<div><dt>${name}</dt><dd title="${hash}">${hash}</dd></div>`).join("");}
  function updateDownloads(job){const names=Object.keys(job.artifacts);$("downloads").className="downloads";$("downloads").innerHTML="";for(const name of names){const item=job.artifacts[name],link=document.createElement("a");link.className="download-card";link.href="#";link.innerHTML=`<strong>${name}</strong><span>${item.bytes.length.toLocaleString()} bytes · ${item.type}</span>`;link.addEventListener("click",event=>{event.preventDefault();C.download(item.bytes,`SPECTRAL_PA_${job.id}_${name}`,item.type);});$("downloads").appendChild(link);}}
  function installAudio(job){if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=C.blobUrl(job.wavBytes,"audio/wav");$("audio").src=audioUrl;$("play").disabled=false;$("stop").disabled=false;$("transport-time").textContent="00:00.000 / "+time(job.fingerprint.frames/job.profile.sampleRate);}
  async function finishJob(job,persist){currentJob=job;updateVisuals(job);updateMetrics(job);updateDownloads(job);installAudio(job);setStatus(`COMPLETE · ${job.recipe.preset_id} · contract ${job.contractHash.slice(0,16)}…`);$("render-time").textContent="SEALED";if(persist){try{await S.save(job);}catch(error){$("storage-status").textContent="STORAGE · SESSION ONLY";$("storage-status").className="status-chip warn";}}await refreshHistory();}
  async function renderConfig(config,replayManifest){abortController=new AbortController();lockControls(true);$("render").disabled=true;$("cancel").disabled=false;$("progress").style.width="0%";$("progress-track").setAttribute("aria-valuenow","0");const started=performance.now();try{const options={signal:abortController.signal,progress:(fraction,label)=>{const percent=Math.round(fraction*100);$("progress").style.width=(fraction*100).toFixed(1)+"%";$("progress-track").setAttribute("aria-valuenow",String(percent));setStatus(label.toUpperCase());$("render-time").textContent=((performance.now()-started)/1000).toFixed(1)+" s";}},job=replayManifest?await P.replay(replayManifest,config.source,options):await P.render(config,options);await finishJob(job,true);}catch(error){if(error.name==="AbortError")setStatus("CANCELLED · no partial artifacts were created",true);else{setStatus("ERROR · "+String(error.message||error),true);console.error(error);}}finally{lockControls(false);$("render").disabled=false;$("cancel").disabled=true;abortController=null;}}
  async function renderCurrent(){try{await renderConfig(buildConfig(),null);}catch(error){setStatus("ERROR · "+String(error.message||error),true);}}
  async function replayFile(file){if(!file)return;try{const manifest=JSON.parse(await file.text());P.verifyManifest(manifest);if(manifest.recipe.source&&(!source||source.hash!==manifest.recipe.source.sha256||source.byteLength!==manifest.recipe.source.byte_length))throw new Error("Load the exact source WAV named by this manifest before replay");applyRecipeToUI(manifest.recipe);const config=P.configFromRecipe(manifest.recipe,manifest.recipe.source?source:null);await renderConfig(config,manifest);}catch(error){setStatus("REPLAY REJECTED · "+String(error.message||error),true);}}
  function cell(row,text){const value=document.createElement("td");value.textContent=String(text);row.appendChild(value);return value;}
  async function refreshHistory(){const records=await S.list();if(!records.length){$("history").className="history empty";$("history").textContent="No locally persisted renders.";return;}$("history").className="history";const table=document.createElement("table");table.innerHTML="<thead><tr><th>Preset</th><th>Mode</th><th>Duration</th><th>WAV</th><th>Local action</th></tr></thead><tbody></tbody>";for(const record of records){const row=document.createElement("tr"),duration=record.frames/record.sampleRate;cell(row,record.presetId);cell(row,record.mode);cell(row,duration.toFixed(2)+" s");const hashCell=cell(row,record.wavHash.slice(0,12)+"…");hashCell.title=record.wavHash;hashCell.className="hash-cell";const action=cell(row,"");const button=document.createElement("button");button.textContent="DOWNLOAD ZIP";button.addEventListener("click",()=>C.download(new Uint8Array(record.bundleBytes),`SPECTRAL_PA_${record.id}_photoacoustic_provenance.zip`,"application/zip"));action.appendChild(button);table.tBodies[0].appendChild(row);}$("history").replaceChildren(table);}
  function listeners(){
    const rack=document.querySelector(".control-rack");rack.addEventListener("input",markStale);rack.addEventListener("change",markStale);
    $("preset").addEventListener("change",()=>applyPreset($("preset").value));$("material").addEventListener("change",()=>loadMaterial($("material").value));$("resonator").addEventListener("change",()=>loadResonator($("resonator").value));$("mode").addEventListener("change",modeNote);$("source-file").addEventListener("change",async event=>{try{await loadSource(event.target.files[0]);}catch(error){setStatus("WAV REJECTED · "+error.message,true);source=null;}});$("render").addEventListener("click",renderCurrent);$("cancel").addEventListener("click",()=>abortController&&abortController.abort());$("reset").addEventListener("click",()=>{applyPreset($("preset").value);markStale();});$("manifest-file").addEventListener("change",event=>replayFile(event.target.files[0]));
    for(const label of [document.querySelector("label[for='source-file']"),document.querySelector(".manifest-load")])label.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();const input=label.htmlFor?$(label.htmlFor):$("manifest-file");input.click();}});
    $("frequency-scale").addEventListener("change",()=>currentJob&&V.spectrogram($("spectrogram"),currentJob.monoPcm,currentJob.profile.sampleRate,$("frequency-scale").value));
    const tabs=Array.from(document.querySelectorAll("[data-stage]"));function selectStage(button){for(const tab of tabs){const selected=tab===button;tab.classList.toggle("active",selected);tab.setAttribute("aria-selected",String(selected));tab.tabIndex=selected?0:-1;}activeStage=button.dataset.stage;$("stage-caption").textContent=captions[activeStage];$("stage-trace").setAttribute("aria-label",captions[activeStage]);if(currentJob)V.trace($("stage-trace"),currentJob.traces[activeStage],activeStage.toUpperCase());}for(const button of tabs){button.addEventListener("click",()=>selectStage(button));button.addEventListener("keydown",event=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();let index=tabs.indexOf(button);if(event.key==="ArrowLeft")index=(index-1+tabs.length)%tabs.length;if(event.key==="ArrowRight")index=(index+1)%tabs.length;if(event.key==="Home")index=0;if(event.key==="End")index=tabs.length-1;selectStage(tabs[index]);tabs[index].focus();});}tabs.forEach((tab,index)=>tab.tabIndex=index? -1:0);
    $("play").addEventListener("click",()=>$("audio").play());$("stop").addEventListener("click",()=>{$("audio").pause();$("audio").currentTime=0;});$("audio").addEventListener("timeupdate",()=>{$("transport-time").textContent=time($("audio").currentTime)+" / "+time($("audio").duration);});$("clear-history").addEventListener("click",async()=>{await S.clear();await refreshHistory();});let resizeTimer;root.addEventListener("resize",()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(currentJob)updateVisuals(currentJob);},120);});
  }
  async function init(){populateRegistry();listeners();applyPreset("industrial-fib");modeNote();V.placeholder($("waveform"),"PCM16 WAVEFORM");V.placeholder($("spectrogram"),"FFT SPECTROGRAM");V.placeholder($("stage-trace"),"MODEL STAGE");const status=await S.init();if(status.supported){const test=await S.selfTest();$("storage-status").textContent=test.passed?"STORAGE · INDEXEDDB":"STORAGE · SESSION ONLY";$("storage-status").className="status-chip "+(test.passed?"ok":"warn");}else{$("storage-status").textContent="STORAGE · SESSION ONLY";$("storage-status").className="status-chip warn";}await refreshHistory();}
  PA.UI=Object.freeze({init,buildConfig,applyPreset,getSource:()=>source,getCurrentJob:()=>currentJob});
})(window);
