(function(root){
  "use strict";
  const PA=root.PHOTOACOUSTIC;
  function setup(canvas){const rect=canvas.getBoundingClientRect(),width=Math.max(320,Math.round(rect.width||canvas.width)),height=Math.max(160,Math.round(rect.height||canvas.height));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}const ctx=canvas.getContext("2d");ctx.setTransform(1,0,0,1,0,0);return{ctx,width,height};}
  function base(ctx,width,height,title){ctx.fillStyle="#080c0e";ctx.fillRect(0,0,width,height);ctx.strokeStyle="#1c292e";ctx.lineWidth=1;for(let i=1;i<8;i+=1){const x=Math.round(i*width/8)+.5;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let i=1;i<4;i+=1){const y=Math.round(i*height/4)+.5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}ctx.fillStyle="#60747a";ctx.font="11px ui-monospace, monospace";ctx.fillText(title,10,17);}
  function placeholder(canvas,text){const{ctx,width,height}=setup(canvas);base(ctx,width,height,text);ctx.fillStyle="#405157";ctx.font="12px ui-monospace, monospace";ctx.textAlign="center";ctx.fillText("NO RENDER",width/2,height/2);ctx.textAlign="left";}
  function waveform(canvas,samples,sampleRate){const{ctx,width,height}=setup(canvas);base(ctx,width,height,"PCM16 · "+sampleRate+" Hz");const mid=height/2;ctx.strokeStyle="#e9a83c";ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<width;x+=1){const start=Math.floor(x*samples.length/width),end=Math.max(start+1,Math.floor((x+1)*samples.length/width));let lo=32767,hi=-32768;for(let i=start;i<end;i+=1){lo=Math.min(lo,samples[i]);hi=Math.max(hi,samples[i]);}ctx.moveTo(x,mid-hi/32768*(height*.43));ctx.lineTo(x,mid-lo/32768*(height*.43));}ctx.stroke();ctx.strokeStyle="#557078";ctx.beginPath();ctx.moveTo(0,mid+.5);ctx.lineTo(width,mid+.5);ctx.stroke();ctx.fillStyle="#60747a";ctx.font="11px ui-monospace, monospace";ctx.fillText("0 s",8,height-8);ctx.textAlign="right";ctx.fillText((samples.length/sampleRate).toFixed(3)+" s",width-8,height-8);ctx.textAlign="left";}
  function trace(canvas,samples,label){const{ctx,width,height}=setup(canvas);base(ctx,width,height,label);if(!samples||!samples.length)return;ctx.strokeStyle="#63c4c8";ctx.lineWidth=1.5;ctx.beginPath();for(let x=0;x<width;x+=1){const index=Math.min(samples.length-1,Math.floor(x*samples.length/width)),y=height/2-samples[index]*height*.42;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.strokeStyle="#936b2b";ctx.beginPath();ctx.moveTo(0,height/2+.5);ctx.lineTo(width,height/2+.5);ctx.stroke();}
  function fft(real,imag){const n=real.length;for(let i=1,j=0;i<n;i+=1){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[real[i],real[j]]=[real[j],real[i]];[imag[i],imag[j]]=[imag[j],imag[i]];}}for(let len=2;len<=n;len<<=1){const angle=-2*Math.PI/len,wlenR=Math.cos(angle),wlenI=Math.sin(angle);for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<len/2;j+=1){const uR=real[i+j],uI=imag[i+j],vR=real[i+j+len/2]*wr-imag[i+j+len/2]*wi,vI=real[i+j+len/2]*wi+imag[i+j+len/2]*wr;real[i+j]=uR+vR;imag[i+j]=uI+vI;real[i+j+len/2]=uR-vR;imag[i+j+len/2]=uI-vI;const next=wr*wlenR-wi*wlenI;wi=wr*wlenI+wi*wlenR;wr=next;}}}}
  function color(value){const v=Math.max(0,Math.min(1,value));if(v<.45){const k=v/.45;return[Math.round(8+70*k),Math.round(12+50*k),Math.round(14+25*k)];}if(v<.82){const k=(v-.45)/.37;return[Math.round(78+155*k),Math.round(62+102*k),Math.round(39+22*k)];}const k=(v-.82)/.18;return[Math.round(233+20*k),Math.round(164+68*k),Math.round(61+145*k)];}
  function spectrogram(canvas,samples,sampleRate,scale){const{ctx,width,height}=setup(canvas);ctx.fillStyle="#080c0e";ctx.fillRect(0,0,width,height);const fftSize=1024,hop=Math.max(1,Math.floor(Math.max(1,samples.length-fftSize)/Math.max(1,width))),columns=Math.min(width,Math.max(1,Math.floor((samples.length-fftSize)/hop)+1)),image=ctx.createImageData(columns,height),real=new Float64Array(fftSize),imag=new Float64Array(fftSize);for(let column=0;column<columns;column+=1){const start=Math.min(Math.max(0,samples.length-fftSize),column*hop);for(let i=0;i<fftSize;i+=1){const window=.5-.5*Math.cos(2*Math.PI*i/(fftSize-1));real[i]=(samples[start+i]||0)/32768*window;imag[i]=0;}fft(real,imag);for(let y=0;y<height;y+=1){const normalized=1-y/(height-1);let frequency;if(scale==="log"){const min=20,max=sampleRate/2;frequency=min*Math.pow(max/min,normalized);}else frequency=normalized*sampleRate/2;const bin=Math.max(0,Math.min(fftSize/2-1,Math.round(frequency/sampleRate*fftSize))),magnitude=Math.sqrt(real[bin]*real[bin]+imag[bin]*imag[bin])/fftSize,db=20*Math.log10(magnitude+1e-8),value=(db+90)/90,[r,g,b]=color(value),offset=(y*columns+column)*4;image.data[offset]=r;image.data[offset+1]=g;image.data[offset+2]=b;image.data[offset+3]=255;}}const temp=document.createElement("canvas");temp.width=columns;temp.height=height;temp.getContext("2d").putImageData(image,0,0);ctx.imageSmoothingEnabled=true;ctx.drawImage(temp,0,0,width,height);ctx.fillStyle="rgba(8,12,14,.75)";ctx.fillRect(0,0,92,22);ctx.fillStyle="#d0dddd";ctx.font="11px ui-monospace, monospace";ctx.fillText((scale==="log"?"LOG":"LINEAR")+" · 1024 FFT",8,15);}
  PA.Visuals=Object.freeze({placeholder,waveform,trace,spectrogram});
})(window);
