(function(PA){
  "use strict";
  const C=PA.Core,A=PA.Audio,M=PA.Model,P=PA.Provenance,S=PA.Storage,tests=[],results=[];
  function add(name,fn){tests.push({name,fn});}function equal(actual,expected,label){if(actual!==expected)throw new Error((label?label+": ":"")+`expected ${expected}, received ${actual}`);}function truth(value,label){if(!value)throw new Error(label||"assertion failed");}function bytesEqual(a,b){equal(a.length,b.length,"byte length");for(let i=0;i<a.length;i+=1)if(a[i]!==b[i])throw new Error(`byte ${i}: ${a[i]} !== ${b[i]}`);}
  function config(presetId,durationSamples,mode){const p=M.PRESETS[presetId];return{mode:mode||PA.MODES.STRICT,seed:"PA-KAT-v1",mutation:0,presetId:p.id,profile:"archive",sampleRate:44100,durationSamples:durationSamples||11025,generator:{type:p.generator,bpmMilli:p.bpmMilli,toneMilli:220000,pulse1Milli:p.pulse1Milli,pulse2Milli:p.pulse2Milli,pulseWidthUs:p.pulseWidthUs,fibDepth:p.fibDepth,pulseShape:p.shape},material:M.copyMaterial(p.material),resonator:M.copyResonator(p.resonator),laserPowerPpm:p.laserPowerPpm,derivative:p.derivative,fx:Object.assign({},p.fx),source:null};}
  function pcmFixture(bits,sampleBytes,includePad){const pad=sampleBytes.length&1,total=44+sampleBytes.length+(includePad===false?0:pad),out=new Uint8Array(total),view=new DataView(out.buffer);function text(offset,value){for(let i=0;i<value.length;i+=1)view.setUint8(offset+i,value.charCodeAt(i));}text(0,"RIFF");view.setUint32(4,total-8,true);text(8,"WAVE");text(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,8000*bits/8,true);view.setUint16(32,bits/8,true);view.setUint16(34,bits,true);text(36,"data");view.setUint32(40,sampleBytes.length,true);out.set(sampleBytes,44);return out;}
  add("SHA-256 · standard vectors",()=>{equal(C.sha256Hex(new Uint8Array()),"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");equal(C.sha256Hex(C.utf8("abc")),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");});
  add("Canonical JSON · lexical object order and integer boundary",()=>{equal(C.stableStringify({z:[3,true],a:"φ"}),'{"a":"φ","z":[3,true]}');let rejected=false;try{C.stableStringify({x:1.5});}catch(_){rejected=true;}truth(rejected,"non-integer canonical number was accepted");});
  add("Canonical decimal · half-away rounding",()=>{equal(C.decimalToScaled("0.125",100),13);equal(C.decimalToScaled("-0.125",100),-13);equal(C.decimalToScaled("4.5e1",1000),45000);});
  add("Strict oscillator · fixed integer quadrants",()=>{equal(C.strictSinQ15(0),0);truth(C.strictSinQ15(0x40000000)>32000);equal(C.strictSinQ15(0x80000000),0);truth(C.strictSinQ15(0xc0000000)<-32000);});
  add("WAV writer · hand-built PCM16 known answer",()=>{const encoded=A.encodePcm16(new Int16Array([-32768,-1,0,1,32767]),8000,1);equal(encoded.wavBytes.length,54);equal(C.sha256Hex(encoded.wavBytes),"19720469d8ea90b29b143393c9138abc454576338bd507d992fc654c56909692");truth(A.validate(encoded.wavBytes));bytesEqual(encoded.wavBytes.slice(44),new Uint8Array([0,128,255,255,0,0,1,0,255,127]));});
  add("WAV parser · canonical round trip",()=>{const source=new Int16Array([-32768,-12000,0,12000,32767]),encoded=A.encodePcm16(source,8000,1),parsed=A.parse(encoded.wavBytes);equal(parsed.sampleRate,8000);equal(parsed.bitsPerSample,16);equal(parsed.frames,5);for(let i=0;i<source.length;i+=1)equal(parsed.samplesQ15[i],source[i]);truth(parsed.strictCompatible);});
  add("WAV parser · PCM24/32 positive extrema clamp to Q15",()=>{const p24=A.parse(pcmFixture(24,new Uint8Array([255,255,127]))),p32=A.parse(pcmFixture(32,new Uint8Array([255,255,255,127])));equal(p24.samplesQ15[0],32767);equal(p32.samplesQ15[0],32767);});
  add("WAV parser · missing odd-chunk pad fails closed",()=>{let rejected=false;try{A.parse(pcmFixture(24,new Uint8Array([1,2,3]),false));}catch(_){rejected=true;}truth(rejected);});
  add("Strict resampler · explicit linear interpolation",()=>{const out=A.resampleStrict(new Int32Array([0,1000,2000]),2,4);equal(Array.from(out).join(","),"0,500,1000,1500,2000,2000");});
  add("Registry · original material parameters",()=>{const m=M.MATERIALS;equal(m.soot.tauUs,1500);equal(m.charcoal.nonlinearityPpm,250000);equal(m.gas_ethene.gruneisenPpm,800000);equal(m.pdms_composite.tauUs,300);equal(m.black_aluminum.absorptionPpm,850000);});
  add("Registry · original resonator modes",()=>{equal(M.RESONATORS.jar.frequenciesMilli.join(","),"180000,360000,720000,1100000");equal(M.RESONATORS.industrial_pipe.qMilli.join(","),"12000,10000,8000,6000,4000");equal(M.RESONATORS.open_air.qMilli[0],700);});
  add("Registry · nested preset data is immutable",()=>{for(const value of Object.values(M.PRESETS)){truth(Object.isFrozen(value));truth(Object.isFrozen(value.fx));}});
  add("Validation · mismatched mode/Q arrays fail closed",()=>{const c=config("industrial-fib",1000);c.resonator.qMilli=c.resonator.qMilli.slice(1);let rejected=false;try{M.validate(c);}catch(_){rejected=true;}truth(rejected);});
  add("Validation · unknown generator and extreme pulse budget fail closed",()=>{const unknown=config("pulse-lab",44100);unknown.generator.type="not-a-generator";let rejected=false;try{M.validate(unknown);}catch(_){rejected=true;}truth(rejected,"unknown generator accepted");const extreme=config("pulse-lab",44100*120);extreme.generator.pulse1Milli=500000;extreme.generator.pulseWidthUs=250000;rejected=false;try{M.validate(extreme);}catch(_){rejected=true;}truth(rejected,"pathological pulse budget accepted");});
  add("Recipe normalization · unused generator controls are excluded",()=>{const a=config("tone-lab",1103),b=config("tone-lab",1103);b.generator.bpmMilli=299000;b.generator.pulse1Milli=499000;equal(P.recipeFromConfig(a).generator.type,"tone");equal(P.recipeFromConfig(a).generator.bpmMilli,undefined);equal(C.stableStringify(P.recipeFromConfig(a)),C.stableStringify(P.recipeFromConfig(b)));});
  add("Canonical Strict · frozen end-to-end golden",async()=>{const job=await P.render(config("industrial-fib",11025),{});equal(job.recipeHash,"c2c161c96a30e575f10a36b3c14e7d9fc6f65710d1052f5072fd8ffa001ec495");equal(job.pcmHash,"fd949fa68df6f1947f3833151fc1c0797f68f36ceeffdcd493c13fe8133fd3d0");equal(job.wavHash,"55b975e30ebfdd98b96a18f59ecbea081770ba2b43fc4ab8f08b0bb3f72c405e");equal(job.fingerprintHash,"b98a4e6a52eccfac553eac74b5d406429c874d32dfe05158510cd0dee901f399");equal(job.stageHash,"e724390c7027f519ace3effcdeaccdeb20fc22785069647a2207ada677c9fcb0");equal(job.contractHash,"08301e0fb2c57be5fbb297be8ddb42c605547cf5b5f5cafa6570012e63bde641");equal(job.manifestCoreHash,"8d15f66ac62c9089c1a66eb6797318a8cb680688e84c749a6f86c5b7ea1802f6");equal(C.sha256Hex(job.bundleBytes),"96aeb8ad1945d376c31d3aeaafacc32b645857bfb010f2548b864ab86b44548d");equal(job.fingerprint.frames,11025);});
  add("Canonical Strict · repeat is byte-identical",async()=>{const a=await P.render(config("industrial-fib",2205),{}),b=await P.render(config("industrial-fib",2205),{});bytesEqual(a.wavBytes,b.wavBytes);equal(a.contractHash,b.contractHash);});
  add("Mutation · changes recipe and WAV identity",async()=>{const a=config("tone-lab",2205),b=config("tone-lab",2205);b.mutation=1;const first=await P.render(a,{}),second=await P.render(b,{});truth(first.recipeHash!==second.recipeHash);truth(first.wavHash!==second.wavHash);});
  add("Determinism mode · separates recipe identity",async()=>{const strict=await P.render(config("tone-lab",2205,PA.MODES.STRICT),{}),replay=await P.render(config("tone-lab",2205,PA.MODES.REPLAY),{});truth(strict.recipeHash!==replay.recipeHash);truth(strict.contractHash!==replay.contractHash);});
  add("Presets · all original mappings render valid WAV",async()=>{for(const id of ["industrial-fib","soot-music","resonant-gas","ultrasonic-edge","drone-dark"]){const job=await P.render(config(id,1103),{});truth(A.validate(job.wavBytes),id);truth(job.fingerprint.peak_q15>0,id+" silence");}});
  add("Material/resonator matrix · finite bounded outputs",async()=>{const materials=["soot","charcoal","gas_ethene","pdms_composite","black_aluminum"],resonators=["jar","helmholtz","h_cell","open_air","industrial_pipe"];for(const material of materials)for(const resonator of resonators){const c=config("tone-lab",512);c.sampleRate=8000;c.durationSamples=512;c.material=M.copyMaterial(material);c.resonator=M.copyResonator(resonator);const kept=c.resonator.frequenciesMilli.map((value,index)=>({value,q:c.resonator.qMilli[index]})).filter(mode=>mode.value<Math.floor(c.sampleRate*1000/6));c.resonator.frequenciesMilli=kept.map(mode=>mode.value);c.resonator.qMilli=kept.map(mode=>mode.q);const result=await M.render(c,{});truth(result.signal.length===512);for(const value of result.signal)truth(Number.isFinite(value),material+"/"+resonator);}});
  add("Manifest replay · verifies exact strict identity",async()=>{const original=await P.render(config("pulse-lab",2205),{}),replayed=await P.replay(original.manifest,null,{});equal(replayed.wavHash,original.wavHash);equal(replayed.contractHash,original.contractHash);equal(replayed.manifestCoreHash,original.manifestCoreHash);});
  add("Source-backed replay · exact WAV required",async()=>{const sourceBytes=A.encodePcm16(new Int16Array([0,12000,-12000,8000,-8000,0]),8000,1).wavBytes,decoded=A.parse(sourceBytes),source=Object.assign(decoded,{hash:C.sha256Hex(sourceBytes),byteLength:sourceBytes.length,bytes:sourceBytes}),c=config("wav-through",Math.max(2,Math.round(decoded.frames*44100/8000)));c.source=source;const original=await P.render(c,{}),replayed=await P.replay(original.manifest,source,{});equal(replayed.wavHash,original.wavHash);const changedBytes=A.encodePcm16(new Int16Array([0,12000,-12000,8000,-7000,0]),8000,1).wavBytes,changed=Object.assign(A.parse(changedBytes),{hash:C.sha256Hex(changedBytes),byteLength:changedBytes.length,bytes:changedBytes});let rejected=false;try{await P.replay(original.manifest,changed,{});}catch(_){rejected=true;}truth(rejected,"changed source accepted");});
  add("Manifest replay · tamper is rejected",async()=>{const original=await P.render(config("tone-lab",1103),{}),tampered=JSON.parse(C.prettyStable(original.manifest));tampered.recipe.seed="changed";let rejected=false;try{P.verifyManifest(tampered);}catch(_){rejected=true;}truth(rejected,"tampered manifest passed verification");});
  add("Cancellation · produces no completed artifact",async()=>{const controller=new AbortController(),pending=P.render(config("drone-dark",44100*2),{signal:controller.signal});setTimeout(()=>controller.abort(),0);let cancelled=false;try{await pending;}catch(error){cancelled=error.name==="AbortError";}truth(cancelled,"render did not cancel");});
  add("Cancellation · late sealing checkpoint aborts",async()=>{const controller=new AbortController();let late=false,cancelled=false;try{await P.render(config("tone-lab",44100),{signal:controller.signal,progress:fraction=>{if(fraction>=.988&&!late){late=true;controller.abort();}}});}catch(error){cancelled=error.name==="AbortError";}truth(late&&cancelled,"late-stage cancellation did not fail closed");});
  add("Deterministic ZIP · entry order does not affect bytes",()=>{const one=A.zip([{name:"b.txt",bytes:C.utf8("B")},{name:"a.txt",bytes:C.utf8("A")}]),two=A.zip([{name:"a.txt",bytes:C.utf8("A")},{name:"b.txt",bytes:C.utf8("B")}]);bytesEqual(one,two);equal(C.sha256Hex(one),C.sha256Hex(two));});
  add("IndexedDB · local ArrayBuffer round trip",async()=>{const status=await S.init();if(!status.supported)return"SKIP: IndexedDB unavailable for this file origin";const result=await S.selfTest();truth(result.passed,result.reason);});
  add("Resource audit · no network attempt or remote resource",()=>{equal((window.__PA_NETWORK_ATTEMPTS__||[]).length,0,(window.__PA_NETWORK_ATTEMPTS__||[]).join(", "));const remote=performance.getEntriesByType("resource").map(entry=>entry.name).filter(name=>/^(?:https?|wss?):/i.test(name));equal(remote.length,0,remote.join(", "));const remoteNodes=Array.from(document.querySelectorAll("[src],[href]")).map(node=>node.getAttribute("src")||node.getAttribute("href")).filter(value=>/^(?:https?|wss?):/i.test(value||""));equal(remoteNodes.length,0,remoteNodes.join(", "));});
  function row(result){const tr=document.createElement("tr"),state=result.skip?"skip":result.pass?"pass":"fail",detail=result.error?"<pre>"+String(result.error.stack||result.error).replace(/[&<>]/g,value=>({"&":"&amp;","<":"&lt;",">":"&gt;"})[value])+"</pre>":(result.note||"OK");tr.innerHTML=`<td class="${state}">${state.toUpperCase()}</td><td>${result.name}</td><td>${detail}</td>`;return tr;}
  window.addEventListener("DOMContentLoaded",async()=>{document.getElementById("runtime").textContent=navigator.userAgent;for(const test of tests){let result;try{const note=await test.fn();result={name:test.name,pass:true,skip:typeof note==="string"&&note.startsWith("SKIP"),note:note||"OK"};}catch(error){result={name:test.name,pass:false,error};}results.push(result);document.getElementById("results").appendChild(row(result));document.getElementById("counts").textContent=results.filter(value=>value.pass).length+" / "+tests.length;}const passed=results.every(value=>value.pass),status=document.getElementById("status");status.textContent=passed?"ALL TESTS PASS":"TEST FAILURE";status.className="status-chip "+(passed?"ok":"warn");document.documentElement.dataset.testStatus=passed?"pass":"fail";window.__PA_TEST_RESULT__={passed,total:tests.length,failed:results.filter(value=>!value.pass).map(value=>value.name)};});
})(window.PHOTOACOUSTIC);
